const rawProverbs = [
  { id: 'better-late-than-never', en: { saying: 'Better late than never', explanation: 'It is better to do something late than not do it at all.' }, dk: { saying: 'Bedre sent end aldrig', explanation: 'Det er bedre at gøre noget sent end slet ikke.' }, fo: { saying: 'Betri seint enn ongantíð', explanation: 'Tað er betri at gera okkurt seint enn als ikki.' } },
  { id: 'actions-speak-louder', en: { saying: 'Actions speak louder than words', explanation: 'What people do matters more than what they say.' }, dk: { saying: 'Handlinger taler højere end ord', explanation: 'Det man gør, betyder mere end det man siger.' }, fo: { saying: 'Gerðir tala hægri enn orð', explanation: 'Tað fólk gera, hevur størri týdning enn tað tey siga.' } },
  { id: 'dont-judge-book', en: { saying: 'Do not judge a book by its cover', explanation: 'Do not judge something only by how it looks.' }, dk: { saying: 'Døm ikke bogen på omslaget', explanation: 'Vurder ikke noget kun ud fra udseendet.' }, fo: { saying: 'Døm ikki bókina eftir permuna', explanation: 'Met ikki um nakað bert eftir útsjóndini.' } },
  { id: 'two-birds-one-stone', en: { saying: 'Kill two birds with one stone', explanation: 'Solve two things with one action.' }, dk: { saying: 'Slå to fluer med ét smæk', explanation: 'Løse to ting med én handling.' }, fo: { saying: 'Sláa tvær flugur við einum smekki', explanation: 'Loysa tvey mál við einari gerð.' } },
  { id: 'elephant-room', en: { saying: 'The elephant in the room', explanation: 'An obvious problem nobody wants to talk about.' }, dk: { saying: 'Elefanten i rummet', explanation: 'Et tydeligt problem, som ingen vil tale om.' }, fo: { saying: 'Elefanturin í rúminum', explanation: 'Ein eyðsýndur trupulleiki, sum eingin vil tosa um.' } },
  { id: 'all-eggs-one-basket', en: { saying: 'Do not put all your eggs in one basket', explanation: 'Do not risk everything on one plan.' }, dk: { saying: 'Læg ikke alle æg i én kurv', explanation: 'Sats ikke alt på én plan.' }, fo: { saying: 'Legg ikki øll eggini í eina kurv', explanation: 'Set ikki alt upp á eina ætlan.' } },
  { id: 'early-bird', en: { saying: 'The early bird catches the worm', explanation: 'People who act early often get the best chances.' }, dk: { saying: 'Morgenstund har guld i mund', explanation: 'Den der er tidligt ude, får ofte de bedste muligheder.' }, fo: { saying: 'Morgunstund hevur gull í munni', explanation: 'Tann sum er tíðliga úti, fær ofta bestu møguleikarnar.' } },
  { id: 'practice-perfect', en: { saying: 'Practice makes perfect', explanation: 'You improve by practicing.' }, dk: { saying: 'Øvelse gør mester', explanation: 'Man bliver bedre ved at øve sig.' }, fo: { saying: 'Venjing ger meistara', explanation: 'Tú verður betri við at venja.' } },
  { id: 'rome-not-built-day', en: { saying: 'Rome was not built in a day', explanation: 'Big things take time.' }, dk: { saying: 'Rom blev ikke bygget på én dag', explanation: 'Store ting tager tid.' }, fo: { saying: 'Róm varð ikki bygdur eftir einum degi', explanation: 'Stór ting taka tíð.' } },
  { id: 'no-smoke-without-fire', en: { saying: 'There is no smoke without fire', explanation: 'Rumors often have a reason behind them.' }, dk: { saying: 'Ingen røg uden ild', explanation: 'Rygter har ofte en årsag bag sig.' }, fo: { saying: 'Eingin roykur uttan eld', explanation: 'Søgur hava ofta eina orsøk aftanfyri seg.' } },
  { id: 'old-habits-die-hard', en: { saying: 'Old habits die hard', explanation: 'It is difficult to change habits.' }, dk: { saying: 'Gamle vaner er svære at bryde', explanation: 'Det er svært at ændre vaner.' }, fo: { saying: 'Gamlar vanar eru torførar at bróta', explanation: 'Tað er torført at broyta vanar.' } },
  { id: 'strike-iron-hot', en: { saying: 'Strike while the iron is hot', explanation: 'Act while the opportunity is good.' }, dk: { saying: 'Smed mens jernet er varmt', explanation: 'Handl mens muligheden er god.' }, fo: { saying: 'Smíð meðan jarnið er heitt', explanation: 'Ger nakað meðan møguleikin er góður.' } },
  { id: 'too-many-cooks', en: { saying: 'Too many cooks spoil the broth', explanation: 'Too many people controlling something can make it worse.' }, dk: { saying: 'For mange kokke fordærver maden', explanation: 'For mange der bestemmer, kan gøre resultatet dårligere.' }, fo: { saying: 'Ov nógvir kokkar spilla matin', explanation: 'Ov nógv fólk við stýring kunnu gera úrslitið verri.' } },
  { id: 'look-before-leap', en: { saying: 'Look before you leap', explanation: 'Think before you act.' }, dk: { saying: 'Se dig for, før du springer', explanation: 'Tænk dig om, før du handler.' }, fo: { saying: 'Hygg áðrenn tú leypir', explanation: 'Hugsa teg um, áðrenn tú gert nakað.' } },
  { id: 'many-hands-light-work', en: { saying: 'Many hands make light work', explanation: 'A task is easier when more people help.' }, dk: { saying: 'Mange hænder gør arbejdet let', explanation: 'En opgave bliver lettere, når flere hjælper.' }, fo: { saying: 'Mangar hendur gera arbeiðið lætt', explanation: 'Ein uppgáva verður lættari, tá fleiri hjálpa.' } },
  { id: 'honesty-best-policy', en: { saying: 'Honesty is the best policy', explanation: 'It is usually best to tell the truth.' }, dk: { saying: 'Ærlighed varer længst', explanation: 'Det er som regel bedst at sige sandheden.' }, fo: { saying: 'Ærligheit varir longst', explanation: 'Tað er vanliga best at siga sannleikan.' } },
  { id: 'time-flies', en: { saying: 'Time flies', explanation: 'Time seems to pass very quickly.' }, dk: { saying: 'Tiden flyver', explanation: 'Tiden føles som om den går meget hurtigt.' }, fo: { saying: 'Tíðin flýgur', explanation: 'Tíðin kennist at ganga sera skjótt.' } },
  { id: 'you-live-and-learn', en: { saying: 'You live and you learn', explanation: 'Experience and mistakes teach you.' }, dk: { saying: 'Man lever og lærer', explanation: 'Fejl og oplevelser lærer en noget.' }, fo: { saying: 'Tú livir og lærir', explanation: 'Mistøk og upplivingar læra teg nakað.' } },
  { id: 'easy-come-easy-go', en: { saying: 'Easy come, easy go', explanation: 'Something gained easily can be lost easily.' }, dk: { saying: 'Let kommet, let gået', explanation: 'Noget man nemt får, kan man nemt miste.' }, fo: { saying: 'Lætt komið, lætt farið', explanation: 'Okkurt tú lætt fært, kan tú lætt missa.' } },
  { id: 'no-pain-no-gain', en: { saying: 'No pain, no gain', explanation: 'Progress often requires effort.' }, dk: { saying: 'Ingen smerte, ingen gevinst', explanation: 'Fremskridt kræver ofte indsats.' }, fo: { saying: 'Eingin pína, eingin vinningur', explanation: 'Framgongd krevur ofta stríð.' } },
  { id: 'silence-golden', en: { saying: 'Silence is golden', explanation: 'Sometimes it is best not to speak.' }, dk: { saying: 'Tavshed er guld', explanation: 'Nogle gange er det bedst ikke at sige noget.' }, fo: { saying: 'Tøgn er gull', explanation: 'Onkuntíð er best ikki at siga nakað.' } },
  { id: 'knowledge-power', en: { saying: 'Knowledge is power', explanation: 'Knowing more gives you strength and options.' }, dk: { saying: 'Viden er magt', explanation: 'Mere viden giver styrke og muligheder.' }, fo: { saying: 'Vitan er vald', explanation: 'Meiri vitan gevur styrki og møguleikar.' } },
  { id: 'all-that-glitters', en: { saying: 'All that glitters is not gold', explanation: 'Something attractive is not always valuable.' }, dk: { saying: 'Alt der glimter er ikke guld', explanation: 'Noget der ser godt ud, er ikke altid værdifuldt.' }, fo: { saying: 'Alt sum glitrar er ikki gull', explanation: 'Okkurt sum sær gott út, er ikki altíð virðismikið.' } },
  { id: 'blood-thicker-water', en: { saying: 'Blood is thicker than water', explanation: 'Family ties are often very strong.' }, dk: { saying: 'Blod er tykkere end vand', explanation: 'Familiebånd er ofte meget stærke.' }, fo: { saying: 'Blóð er tjúkkari enn vatn', explanation: 'Familjubond eru ofta sera sterk.' } },
  { id: 'walls-have-ears', en: { saying: 'Walls have ears', explanation: 'Be careful what you say; someone may be listening.' }, dk: { saying: 'Væggene har ører', explanation: 'Pas på hvad du siger; nogen kan lytte med.' }, fo: { saying: 'Veggirnir hava oyru', explanation: 'Ansar eftir hvat tú sigur; onkur kann lurta.' } },
  { id: 'love-blind', en: { saying: 'Love is blind', explanation: 'Love can make people ignore faults.' }, dk: { saying: 'Kærlighed gør blind', explanation: 'Kærlighed kan få folk til at overse fejl.' }, fo: { saying: 'Kærleiki ger blindan', explanation: 'Kærleiki kann fáa fólk at síggja burtur frá brekum.' } },
  { id: 'necessity-invention', en: { saying: 'Necessity is the mother of invention', explanation: 'Need often creates new ideas.' }, dk: { saying: 'Nød lærer nøgen kvinde at spinde', explanation: 'Behov kan få mennesker til at finde nye løsninger.' }, fo: { saying: 'Neyð lærir nakna kvinnu at spinna', explanation: 'Tørvur kann fáa fólk at finna nýggjar loysnir.' } },
  { id: 'where-theres-will', en: { saying: 'Where there is a will, there is a way', explanation: 'Determination can help you find a solution.' }, dk: { saying: 'Hvor der er vilje, er der vej', explanation: 'Vilje kan hjælpe dig med at finde en løsning.' }, fo: { saying: 'Har vilji er, er vegur', explanation: 'Vilji kann hjálpa tær at finna eina loysn.' } },
  { id: 'nothing-ventured', en: { saying: 'Nothing ventured, nothing gained', explanation: 'You must take chances to gain something.' }, dk: { saying: 'Hvo intet vover, intet vinder', explanation: 'Man må tage chancer for at vinde noget.' }, fo: { saying: 'Tann ið einki váðar, einki vinnur', explanation: 'Tú mást váða nakað fyri at vinna nakað.' } },
  { id: 'empty-vessels', en: { saying: 'Empty vessels make the most noise', explanation: 'People with little knowledge can be the loudest.' }, dk: { saying: 'Tomme tønder buldrer mest', explanation: 'Folk med lidt indhold kan larme mest.' }, fo: { saying: 'Tóm íløt ljóða mest', explanation: 'Fólk við lítlari vitan kunnu vera mest harðmælt.' } },
  { id: 'slow-steady', en: { saying: 'Slow and steady wins the race', explanation: 'Patience and consistency often win.' }, dk: { saying: 'Langsomt men sikkert vinder løbet', explanation: 'Tålmodighed og stabilitet vinder ofte.' }, fo: { saying: 'Seint og trygt vinnur kapprenningina', explanation: 'Tol og støðufesti vinna ofta.' } },
  { id: 'every-beginning-hard', en: { saying: 'Every beginning is hard', explanation: 'Starting something new can be difficult.' }, dk: { saying: 'Al begyndelse er svær', explanation: 'Det kan være svært at starte noget nyt.' }, fo: { saying: 'Øll byrjan er torfør', explanation: 'Tað kann vera torført at byrja nakað nýtt.' } },
  { id: 'like-father-son', en: { saying: 'Like father, like son', explanation: 'Children often resemble their parents.' }, dk: { saying: 'Som far, så søn', explanation: 'Børn ligner ofte deres forældre.' }, fo: { saying: 'Sum faðir, so sonur', explanation: 'Børn líkjast ofta foreldrunum.' } },
  { id: 'out-of-sight', en: { saying: 'Out of sight, out of mind', explanation: 'People often forget what they do not see.' }, dk: { saying: 'Ude af øje, ude af sind', explanation: 'Man glemmer ofte det, man ikke ser.' }, fo: { saying: 'Úr eygsjón, úr huga', explanation: 'Fólk gloyma ofta tað, tey ikki síggja.' } },
  { id: 'one-swallow', en: { saying: 'One swallow does not make a summer', explanation: 'One good sign does not prove everything is fine.' }, dk: { saying: 'Én svale gør ingen sommer', explanation: 'Et enkelt godt tegn beviser ikke, at alt er godt.' }, fo: { saying: 'Ein svala ger onga summar', explanation: 'Eitt gott tekin prógvar ikki, at alt er gott.' } },
  { id: 'opposites-attract', en: { saying: 'Opposites attract', explanation: 'Very different people can be drawn to each other.' }, dk: { saying: 'Modsætninger mødes', explanation: 'Meget forskellige mennesker kan tiltrækkes af hinanden.' }, fo: { saying: 'Andsøgnir dragast at hvørjum øðrum', explanation: 'Sera ymisk fólk kunnu dragast at hvørjum øðrum.' } },
  { id: 'patience-virtue', en: { saying: 'Patience is a virtue', explanation: 'Being patient is a good quality.' }, dk: { saying: 'Tålmodighed er en dyd', explanation: 'Det er en god egenskab at være tålmodig.' }, fo: { saying: 'Tol er ein dygd', explanation: 'Tað er ein góð eginleiki at hava tol.' } },
  { id: 'truth-will-out', en: { saying: 'The truth will out', explanation: 'The truth usually becomes known eventually.' }, dk: { saying: 'Sandheden kommer for en dag', explanation: 'Sandheden bliver som regel kendt til sidst.' }, fo: { saying: 'Sannleikin kemur fyri ein dag', explanation: 'Sannleikin kemur vanliga fram at enda.' } },
  { id: 'haste-makes-waste', en: { saying: 'Haste makes waste', explanation: 'Doing things too quickly can create mistakes.' }, dk: { saying: 'Hastværk er lastværk', explanation: 'Hvis man skynder sig for meget, laver man fejl.' }, fo: { saying: 'Skundur er ofta skaði', explanation: 'Ger mann okkurt ov skjótt, koma ofta mistøk.' } },
  { id: 'better-safe-than-sorry', en: { saying: 'Better safe than sorry', explanation: 'It is better to be careful than regret it later.' }, dk: { saying: 'Hellere være på den sikre side', explanation: 'Det er bedre at være forsigtig end at fortryde senere.' }, fo: { saying: 'Betri tryggur enn harmur', explanation: 'Tað er betri at vera varin enn at angra seinni.' } },
  { id: 'birds-feather', en: { saying: 'Birds of a feather flock together', explanation: 'Similar people often spend time together.' }, dk: { saying: 'Lige børn leger bedst', explanation: 'Folk der ligner hinanden, finder ofte sammen.' }, fo: { saying: 'Lík børn spæla best', explanation: 'Fólk sum líkjast, finna ofta saman.' } },
  { id: 'better-one-bird', en: { saying: 'A bird in the hand is worth two in the bush', explanation: 'A sure thing is better than a risky possibility.' }, dk: { saying: 'Hellere én fugl i hånden end ti på taget', explanation: 'Noget sikkert er bedre end en usikker mulighed.' }, fo: { saying: 'Betri ein fuglur í hond enn tíggju á takinum', explanation: 'Okkurt trygt er betri enn ein óvissur møguleiki.' } },
  { id: 'after-rain-sun', en: { saying: 'After rain comes sunshine', explanation: 'Hard times are often followed by better times.' }, dk: { saying: 'Efter regn kommer solskin', explanation: 'Svære tider bliver ofte efterfulgt af bedre tider.' }, fo: { saying: 'Eftir regn kemur sólskin', explanation: 'Eftir torførar tíðir koma ofta betri tíðir.' } },
  { id: 'pick-your-brain', en: { saying: 'Can I pick your brain?', explanation: 'A friendly way to ask someone for advice, ideas, or knowledge.', origin: 'The phrase imagines gently taking useful thoughts from someone’s mind. It became common in everyday English in the 1900s.' }, dk: { saying: 'Må jeg lige høre din mening?', explanation: 'En venlig måde at spørge nogen om råd, idéer eller viden.', origin: 'Det engelske udtryk betyder bogstaveligt at “plukke” i nogens hjerne, men bruges uformelt og ikke voldsomt.' }, fo: { saying: 'Kann eg hoyra tína meining?', explanation: 'Ein vinarligur máti at spyrja onkran um ráð, hugskot ella vitan.', origin: 'Enska orðingin merkir bókstaviliga at “plukka” í heilanum hjá onkrum, men verður brúkt óformliga.' } },
  { id: 'bone-to-pick', en: { saying: 'I have a bone to pick with you', explanation: 'You have a complaint or disagreement you want to discuss.', origin: 'It likely comes from two dogs fighting over the same bone, so today it means there is an issue to settle.' }, dk: { saying: 'Jeg har noget at tale med dig om', explanation: 'Du har en klage eller uenighed, som du vil tage op.', origin: 'Udtrykket forbindes ofte med to hunde, der slås om det samme ben — altså noget der skal afklares.' }, fo: { saying: 'Eg havi nakað at tosa við teg um', explanation: 'Tú hevur eina klagu ella ósemju, sum tú vilt taka upp.', origin: 'Orðingin verður ofta knýtt at tveimum hundum, sum stríðast um sama bein — nakað má fáast upp á pláss.' } },
  { id: 'break-the-ice', en: { saying: 'Break the ice', explanation: 'To make a first meeting or awkward situation feel easier.', origin: 'Ships once had to break ice to open a route. The phrase later became social: opening the way for conversation.' }, dk: { saying: 'Bryde isen', explanation: 'At gøre et første møde eller en akavet situation lettere.', origin: 'Skibe måtte bryde is for at åbne en vej. Senere blev det brugt om at åbne en samtale.' }, fo: { saying: 'Bróta ísin', explanation: 'At gera ein fyrsta fund ella eina ótrygga støðu lættari.', origin: 'Skip máttu bróta ís fyri at sleppa fram. Seinni varð tað brúkt um at lata upp fyri samrøðu.' } },
  { id: 'spill-the-beans', en: { saying: 'Spill the beans', explanation: 'To reveal a secret, often by accident.', origin: 'The exact origin is uncertain, but it may come from old voting with beans, where spilling them revealed the result too early.' }, dk: { saying: 'Afsløre hemmeligheden', explanation: 'At røbe en hemmelighed, ofte ved et uheld.', origin: 'Oprindelsen er usikker, men forbindes ofte med gamle afstemninger med bønner, hvor resultatet blev afsløret for tidligt.' }, fo: { saying: 'Avdúka loyndarmálið', explanation: 'At avdúka eitt loyndarmál, ofta av óvart.', origin: 'Upprunin er óvissur, men verður ofta settur í samband við gamlar atkvøður við bønum, har úrslitið kundi síggjast ov tíðliga.' } },
  { id: 'bite-the-bullet', en: { saying: 'Bite the bullet', explanation: 'To accept something painful or difficult and get through it.', origin: 'Before modern anaesthetic, soldiers were sometimes said to bite on a bullet during surgery. The history is debated, but the meaning survived.' }, dk: { saying: 'Bide tænderne sammen', explanation: 'At acceptere noget svært eller ubehageligt og komme igennem det.', origin: 'Udtrykket knyttes ofte til soldater, der bed i en kugle under operationer før moderne bedøvelse. Historien er omdiskuteret.' }, fo: { saying: 'Bíta tenninar saman', explanation: 'At taka okkurt trupult ella pínufult á seg og koma ígjøgnum tað.', origin: 'Orðingin verður ofta knýtt at hermonnum, sum bitu í eina kúlu undir skurðviðgerð áðrenn nútímans doyving. Søgan er tó umrødd.' } },
  { id: 'under-the-weather', en: { saying: 'Under the weather', explanation: 'To feel ill, tired, or not quite yourself.', origin: 'Often linked to sailors who went below deck, under the bad weather, when they felt sick.' }, dk: { saying: 'Ikke helt på toppen', explanation: 'At føle sig syg, træt eller ikke helt som sig selv.', origin: 'Udtrykket forbindes ofte med søfolk, der gik under dæk — væk fra vejret — når de blev søsyge.' }, fo: { saying: 'Ikki heilt væl fyri', explanation: 'At kenna seg sjúkan, móðan ella ikki heilt sum vanligt.', origin: 'Orðingin verður ofta knýtt at sjófólki, sum fóru undir dekk — undir veðrinum — tá tey gjørdust sjóverk.' } },
  { id: 'blessing-in-disguise', en: { saying: 'A blessing in disguise', explanation: 'Something that first seems bad but later turns out to be good.', origin: 'The phrase has been used since at least the 1700s and carries a religious idea: good fortune hidden inside trouble.' }, dk: { saying: 'Et held i uheld', explanation: 'Noget der først virker dårligt, men senere viser sig at være godt.', origin: 'Udtrykket har været brugt siden mindst 1700-tallet og bygger på idéen om en skjult velsignelse.' }, fo: { saying: 'Eitt hepni í óhepni', explanation: 'Okkurt sum fyrst tykist ringt, men seinni vísir seg at vera gott.', origin: 'Orðingin hevur verið brúkt í fleiri øldir og ber hugmyndina um eina goymda signing.' } },
  { id: 'good-samaritan', en: { saying: 'A good Samaritan', explanation: 'Someone who helps a stranger or person in need.', origin: 'From Jesus’ parable in the Gospel of Luke, where a Samaritan helps a wounded traveller when others pass by.' }, dk: { saying: 'En barmhjertig samaritaner', explanation: 'En person der hjælper en fremmed eller én i nød.', origin: 'Fra Jesu lignelse i Lukasevangeliet, hvor en samaritaner hjælper en såret rejsende.' }, fo: { saying: 'Ein miskunnsamur samverji', explanation: 'Ein persónur sum hjálpir einum fremmandum ella einum í neyð.', origin: 'Úr líknilsi Jesusar í Lukasevangeliinum, har ein samverji hjálpir einum særdum ferðamanni.' } },
  { id: 'forbidden-fruit', en: { saying: 'Forbidden fruit', explanation: 'Something becomes more tempting because it is not allowed.', origin: 'From the story of Adam and Eve in Genesis. The fruit is not named as an apple in the Bible, though art often shows it that way.' }, dk: { saying: 'Forbuden frugt', explanation: 'Noget bliver mere fristende, fordi det ikke er tilladt.', origin: 'Fra fortællingen om Adam og Eva i Første Mosebog. Bibelen siger ikke, at frugten var et æble.' }, fo: { saying: 'Forboðin frukt', explanation: 'Okkurt verður meira freistandi, tí tað ikki er loyvt.', origin: 'Úr frásøgnini um Ádam og Evu í Fyrstu Mósebók. Bíblian sigur ikki, at fruktin var eitt súrepli.' } },
  { id: 'scapegoat', en: { saying: 'Scapegoat', explanation: 'A person or group blamed for something, often unfairly.', origin: 'From Leviticus, where a goat symbolically carried the community’s sins into the wilderness.' }, dk: { saying: 'Syndebuk', explanation: 'En person eller gruppe der får skylden, ofte uretfærdigt.', origin: 'Fra Tredje Mosebog, hvor en buk symbolsk bar folkets synder ud i ørkenen.' }, fo: { saying: 'Syndabukkur', explanation: 'Ein persónur ella bólkur, sum fær skyldina, ofta órættvíst.', origin: 'Úr Triðju Mósebók, har ein bukkur ímyndarliga bar syndir fólksins út í oyðimørkina.' } },
  { id: 'skin-of-teeth', en: { saying: 'By the skin of your teeth', explanation: 'To only just succeed or escape.', origin: 'From the Book of Job. It survives today as a vivid way to say “barely”.' }, dk: { saying: 'Med nød og næppe', explanation: 'At klare noget eller slippe væk lige akkurat.', origin: 'Fra Jobs Bog i Bibelen. Udtrykket lever videre som en stærk måde at sige “kun lige”.' }, fo: { saying: 'Við neyð og deyð', explanation: 'At klára okkurt ella sleppa burtur akkurát.', origin: 'Úr Jobs bók í Bíbliuni. Orðingin livir víðari sum ein sterk mynd fyri “bara akkurát”.' } },
  { id: 'no-brainer', en: { saying: 'A no-brainer', explanation: 'An easy decision that does not need much thought.', origin: 'Modern informal English from the late 1900s, built on the idea that the answer is so obvious it hardly needs a brain.' }, dk: { saying: 'En selvfølge', explanation: 'En nem beslutning, der næsten ikke kræver overvejelse.', origin: 'Moderne uformelt engelsk fra slutningen af 1900-tallet: svaret er så oplagt, at man næsten ikke behøver hjernen.' }, fo: { saying: 'Sjálvsagt', explanation: 'Ein løtt avgerð, sum næstan ikki krevur umhugsan.', origin: 'Nýggjari óformelt enskt mál: svarið er so eyðsýnt, at tú næstan ikki nýtir heilan.' } },
  { id: 'hangry', en: { saying: 'Hangry', explanation: 'Irritable or angry because you are hungry.', origin: 'A modern blend of “hungry” and “angry”. It became widely used online and in casual speech.' }, dk: { saying: 'Sulten og sur', explanation: 'Irriteret eller vred, fordi man er sulten.', origin: 'Et moderne slangord sammensat af “hungry” og “angry”, især udbredt online og i hverdagssprog.' }, fo: { saying: 'Svangaður og illur', explanation: 'Irriteraður ella illur, tí tú ert svangur.', origin: 'Eitt nýggjari slangorð úr enskum, sett saman av “hungry” og “angry”.' } },
  { id: 'ghost-someone', en: { saying: 'To ghost someone', explanation: 'To suddenly stop replying to someone without explanation.', origin: 'Modern digital slang: the person disappears from contact like a ghost.' }, dk: { saying: 'At ghoste nogen', explanation: 'Pludselig at stoppe med at svare nogen uden forklaring.', origin: 'Moderne digital slang: personen forsvinder fra kontakten som et spøgelse.' }, fo: { saying: 'At ghosta onkran', explanation: 'Brádliga at gevast at svara onkrum uttan frágreiðing.', origin: 'Nýggjari talgilt slang: persónurin hvørvur sum eitt spøkilsi.' } },
  { id: 'throw-shade', en: { saying: 'Throw shade', explanation: 'To subtly criticize or show disrespect.', origin: 'Popularized through Black and LGBTQ+ ballroom culture, then spread widely through media and social platforms.' }, dk: { saying: 'Kaste skygge', explanation: 'At kritisere eller vise mangel på respekt på en indirekte måde.', origin: 'Udbredt gennem Black og LGBTQ+ ballroom-kultur og senere gennem medier og sociale platforme.' }, fo: { saying: 'Kasta skugga', explanation: 'At finnast at ella vísa vanvirðing á ein óbeinleiðis hátt.', origin: 'Vorðið kent gjøgnum Black og LGBTQ+ ballroom-mentan og seinni gjøgnum miðlar og sosialar pallir.' } }
];

const categoryById = {
  'better-late-than-never': 'wisdom',
  'actions-speak-louder': 'work',
  'dont-judge-book': 'wisdom',
  'two-birds-one-stone': 'work',
  'elephant-room': 'wisdom',
  'all-eggs-one-basket': 'wisdom',
  'early-bird': 'work',
  'practice-perfect': 'work',
  'rome-not-built-day': 'work',
  'no-smoke-without-fire': 'wisdom',
  'old-habits-die-hard': 'life',
  'strike-iron-hot': 'work',
  'too-many-cooks': 'humour',
  'look-before-leap': 'wisdom',
  'many-hands-light-work': 'work',
  'honesty-best-policy': 'wisdom',
  'time-flies': 'life',
  'you-live-and-learn': 'life',
  'easy-come-easy-go': 'life',
  'no-pain-no-gain': 'work',
  'silence-golden': 'wisdom',
  'knowledge-power': 'wisdom',
  'all-that-glitters': 'wisdom',
  'blood-thicker-water': 'life',
  'walls-have-ears': 'wisdom',
  'love-blind': 'love',
  'necessity-invention': 'work',
  'where-theres-will': 'work',
  'nothing-ventured': 'work',
  'empty-vessels': 'wisdom',
  'slow-steady': 'work',
  'every-beginning-hard': 'life',
  'like-father-son': 'life',
  'out-of-sight': 'love',
  'one-swallow': 'weather',
  'opposites-attract': 'love',
  'patience-virtue': 'wisdom',
  'truth-will-out': 'wisdom',
  'haste-makes-waste': 'work',
  'better-safe-than-sorry': 'wisdom',
  'birds-feather': 'life',
  'better-one-bird': 'sea',
  'after-rain-sun': 'weather',
  'pick-your-brain': 'slang',
  'bone-to-pick': 'slang',
  'break-the-ice': 'life',
  'spill-the-beans': 'slang',
  'bite-the-bullet': 'work',
  'under-the-weather': 'weather',
  'blessing-in-disguise': 'biblical',
  'good-samaritan': 'biblical',
  'forbidden-fruit': 'biblical',
  'scapegoat': 'biblical',
  'skin-of-teeth': 'biblical',
  'no-brainer': 'slang',
  'hangry': 'slang',
  'ghost-someone': 'slang',
  'throw-shade': 'slang'
};

export const categories = [
  { key: 'all', label: 'All' },
  { key: 'life', label: 'Life' },
  { key: 'love', label: 'Love' },
  { key: 'work', label: 'Work' },
  { key: 'sea', label: 'Sea' },
  { key: 'weather', label: 'Weather' },
  { key: 'wisdom', label: 'Wisdom' },
  { key: 'biblical', label: 'Biblical' },
  { key: 'slang', label: 'Slang' },
  { key: 'humour', label: 'Humour' }
];

export const proverbs = rawProverbs.map((proverb) => ({
  ...proverb,
  category: categoryById[proverb.id] || 'wisdom'
}));

export const languages = [
  { key: 'en', label: 'EN' },
  { key: 'dk', label: 'DK' },
  { key: 'fo', label: 'FO' }
];
