-- Visay / Proverbs Poison dedicated Supabase setup.
-- Generated from old project data on 2026-06-04.

create extension if not exists pgcrypto;

create table if not exists public.proverbs (
  id text primary key default (gen_random_uuid())::text,
  image_url text,
  category text,
  favorite_count integer not null default 0 check (favorite_count >= 0),
  created_at timestamptz not null default now(),
  quote_en text,
  quote_da text,
  quote_de text,
  quote_es text,
  quote_no text,
  quote_la text,
  quote_it text,
  quote_fr text,
  quote_fo text,
  description_en text,
  description_da text,
  description_de text,
  description_es text,
  description_no text,
  description_la text,
  description_it text,
  description_fr text,
  description_fo text
);

create index if not exists proverbs_created_at_idx on public.proverbs (created_at desc);
create index if not exists proverbs_category_idx on public.proverbs (category);

alter table public.proverbs enable row level security;

drop policy if exists "Public can read proverbs" on public.proverbs;
create policy "Public can read proverbs"
  on public.proverbs
  for select
  using (true);

create or replace function public.adjust_proverb_favorite_count(proverb_id text, amount integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_count integer;
begin
  if amount not in (-1, 1) then
    raise exception 'Favorite count adjustment must be -1 or 1';
  end if;

  update public.proverbs
     set favorite_count = greatest(0, favorite_count + amount)
   where id = proverb_id
   returning favorite_count into next_count;

  if next_count is null then
    raise exception 'Proverb not found: %', proverb_id;
  end if;

  return next_count;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.proverbs to anon, authenticated;
grant execute on function public.adjust_proverb_favorite_count(text, integer) to anon, authenticated;

insert into public.proverbs (id, image_url, category, favorite_count, created_at, quote_en, quote_da, quote_de, quote_es, quote_no, quote_la, quote_it, quote_fr, quote_fo, description_en, description_da, description_de, description_es, description_no, description_la, description_it, description_fr, description_fo)
values
  (E'better-late-than-never', null, E'time', 0, E'2026-06-03T20:37:03.156718+00:00', E'Better late than never', E'Bedre sent end aldrig', E'Besser spät als nie', E'Más vale tarde que nunca', E'Bedre sent enn aldri', E'Potius sero quam numquam', E'Meglio tardi che mai', E'Mieux vaut tard que jamais', E'Betri seint enn ongantíð', E'It is better to do something late than not do it at all.', E'Det er bedre at gøre noget sent end slet ikke.', E'It is better to do something late than not do it at all.', E'It is better to do something late than not do it at all.', E'It is better to do something late than not do it at all.', E'It is better to do something late than not do it at all.', E'It is better to do something late than not do it at all.', E'It is better to do something late than not do it at all.', E'Tað er betri at gera okkurt seint enn als ikki.'),
  (E'early-bird', null, E'time', 0, E'2026-06-03T20:37:04.156718+00:00', E'The early bird catches the worm', E'Morgenstund har guld i mund', E'Morgenstund hat Gold im Mund', E'A quien madruga, Dios le ayuda', E'Morgenstund har gull i munn', E'The early bird catches the worm', E'Il mattino ha l’oro in bocca', E'L’avenir appartient à ceux qui se lèvent tôt', E'Morgunstund hevur gull í munni', E'People who act early often get the best chances.', E'Den der er tidligt ude, får ofte de bedste muligheder.', E'People who act early often get the best chances.', E'People who act early often get the best chances.', E'People who act early often get the best chances.', E'People who act early often get the best chances.', E'People who act early often get the best chances.', E'People who act early often get the best chances.', E'Tann sum er tíðliga úti, fær ofta bestu møguleikarnar.'),
  (E'time-flies', null, E'time', 0, E'2026-06-03T20:37:05.156718+00:00', E'Time flies', E'Tiden flyver', E'Die Zeit fliegt', E'El tiempo vuela', E'Tiden flyr', E'Tempus fugit', E'Il tempo vola', E'Le temps file', E'Tíðin flýgur', E'Time seems to pass very quickly.', E'Tiden føles som om den går meget hurtigt.', E'Time seems to pass very quickly.', E'Time seems to pass very quickly.', E'Time seems to pass very quickly.', E'Time seems to pass very quickly.', E'Time seems to pass very quickly.', E'Time seems to pass very quickly.', E'Tíðin kennist at ganga sera skjótt.'),
  (E'slow-steady', null, E'time', 0, E'2026-06-03T20:37:06.156718+00:00', E'Slow and steady wins the race', E'Langsomt men sikkert vinder løbet', E'Eile mit Weile', E'Sin prisa pero sin pausa', E'Langsomt men sikkert', E'Festina lente', E'Chi va piano va sano e va lontano', E'Qui va doucement va sûrement', E'Seint og trygt vinnur kapprenningina', E'Patience and consistency often win.', E'Tålmodighed og stabilitet vinder ofte.', E'Patience and consistency often win.', E'Patience and consistency often win.', E'Patience and consistency often win.', E'Patience and consistency often win.', E'Patience and consistency often win.', E'Patience and consistency often win.', E'Tol og støðufesti vinna ofta.'),
  (E'haste-makes-waste', null, E'time', 0, E'2026-06-03T20:37:07.156718+00:00', E'Haste makes waste', E'Hastværk er lastværk', E'Eile mit Weile', E'Vísteme despacio, que tengo prisa', E'Hastverk er lastverk', E'Festina lente', E'La gatta frettolosa fece i gattini ciechi', E'Il ne faut pas confondre vitesse et précipitation', E'Skundur er ofta skaði', E'Doing things too quickly can create mistakes.', E'Hvis man skynder sig for meget, laver man fejl.', E'Doing things too quickly can create mistakes.', E'Doing things too quickly can create mistakes.', E'Doing things too quickly can create mistakes.', E'Doing things too quickly can create mistakes.', E'Doing things too quickly can create mistakes.', E'Doing things too quickly can create mistakes.', E'Ger mann okkurt ov skjótt, koma ofta mistøk.'),
  (E'make-hay-sun-shines', null, E'time', 0, E'2026-06-03T20:37:08.156718+00:00', E'Make hay while the sun shines', E'Hø skal bjærges mens solen skinner', E'Make hay while the sun shines', E'Make hay while the sun shines', E'Make hay while the sun shines', E'Make hay while the sun shines', E'Make hay while the sun shines', E'Make hay while the sun shines', E'Ger hoyggj meðan sólin skínur', E'Use a good opportunity while conditions are favorable.', E'Brug muligheden, mens forholdene er gode.', E'Use a good opportunity while conditions are favorable.', E'Use a good opportunity while conditions are favorable.', E'Use a good opportunity while conditions are favorable.', E'Use a good opportunity while conditions are favorable.', E'Use a good opportunity while conditions are favorable.', E'Use a good opportunity while conditions are favorable.', E'Brúka møguleikan, meðan umstøðurnar eru góðar.'),
  (E'falling-knife', null, E'time', 0, E'2026-06-03T20:37:09.156718+00:00', E'A falling knife has no handle', E'En faldende kniv har intet håndtag', E'A falling knife has no handle', E'A falling knife has no handle', E'A falling knife has no handle', E'A falling knife has no handle', E'A falling knife has no handle', E'A falling knife has no handle', E'Ein fallandi knívur hevur einki skaft', E'Do not try to stop a situation while it is moving too fast and dangerously.', E'Prøv ikke at stoppe en situation, mens den falder hurtigt og farligt.', E'Do not try to stop a situation while it is moving too fast and dangerously.', E'Do not try to stop a situation while it is moving too fast and dangerously.', E'Do not try to stop a situation while it is moving too fast and dangerously.', E'Do not try to stop a situation while it is moving too fast and dangerously.', E'Do not try to stop a situation while it is moving too fast and dangerously.', E'Do not try to stop a situation while it is moving too fast and dangerously.', E'Royn ikki at steðga einari støðu, meðan hon fellur skjótt og vandamikið.'),
  (E'hell-keep-going', null, E'time', 0, E'2026-06-03T20:37:10.156718+00:00', E'If you are going through hell, keep going', E'Hvis du går gennem helvede, så bliv ved med at gå', E'If you are going through hell, keep going', E'If you are going through hell, keep going', E'If you are going through hell, keep going', E'If you are going through hell, keep going', E'If you are going through hell, keep going', E'If you are going through hell, keep going', E'Um tú gongur gjøgnum helviti, halt fram at ganga', E'When a situation is awful, do not stop inside it.', E'Når en situation er forfærdelig, skal du ikke slå lejr midt i den.', E'When a situation is awful, do not stop inside it.', E'When a situation is awful, do not stop inside it.', E'When a situation is awful, do not stop inside it.', E'When a situation is awful, do not stop inside it.', E'When a situation is awful, do not stop inside it.', E'When a situation is awful, do not stop inside it.', E'Tá støðan er ræðulig, skalt tú ikki steðga mitt í henni.'),
  (E'actions-speak-louder', null, E'work-results', 0, E'2026-06-03T20:37:11.156718+00:00', E'Actions speak louder than words', E'Handlinger taler højere end ord', E'Taten sagen mehr als Worte', E'Obras son amores, y no buenas razones', E'Handling sier mer enn ord', E'Actions speak louder than words', E'I fatti contano più delle parole', E'Les actes valent mieux que les paroles', E'Gerðir tala hægri enn orð', E'What people do matters more than what they say.', E'Det man gør, betyder mere end det man siger.', E'What people do matters more than what they say.', E'What people do matters more than what they say.', E'What people do matters more than what they say.', E'What people do matters more than what they say.', E'What people do matters more than what they say.', E'What people do matters more than what they say.', E'Tað fólk gera, hevur størri týdning enn tað tey siga.'),
  (E'practice-perfect', null, E'work-results', 0, E'2026-06-03T20:37:12.156718+00:00', E'Practice makes perfect', E'Øvelse gør mester', E'Übung macht den Meister', E'La práctica hace al maestro', E'Øvelse gjør mester', E'Usus magister est optimus', E'La pratica rende perfetti', E'C’est en forgeant qu’on devient forgeron', E'Venjing ger meistara', E'You improve by practicing.', E'Man bliver bedre ved at øve sig.', E'You improve by practicing.', E'You improve by practicing.', E'You improve by practicing.', E'You improve by practicing.', E'You improve by practicing.', E'You improve by practicing.', E'Tú verður betri við at venja.'),
  (E'motion-not-action', null, E'work-results', 0, E'2026-06-03T20:37:13.156718+00:00', E'Never confuse motion with action', E'Forveksl aldrig bevægelse med handling', E'Never confuse motion with action', E'Never confuse motion with action', E'Never confuse motion with action', E'Never confuse motion with action', E'Never confuse motion with action', E'Never confuse motion with action', E'Blanda ongantíð rørslu saman við gerð', E'Being busy is not the same as making real progress.', E'At have travlt er ikke det samme som at skabe reel fremdrift.', E'Being busy is not the same as making real progress.', E'Being busy is not the same as making real progress.', E'Being busy is not the same as making real progress.', E'Being busy is not the same as making real progress.', E'Being busy is not the same as making real progress.', E'Being busy is not the same as making real progress.', E'At hava nógv at gera er ikki tað sama sum verulig framgongd.'),
  (E'opportunity-overalls', null, E'work-results', 0, E'2026-06-03T20:37:14.156718+00:00', E'Opportunity is missed because it is dressed in overalls and looks like work', E'Muligheden bliver overset, fordi den har overalls på og ligner arbejde', E'Opportunity is missed because it is dressed in overalls and looks like work', E'Opportunity is missed because it is dressed in overalls and looks like work', E'Opportunity is missed because it is dressed in overalls and looks like work', E'Opportunity is missed because it is dressed in overalls and looks like work', E'Opportunity is missed because it is dressed in overalls and looks like work', E'Opportunity is missed because it is dressed in overalls and looks like work', E'Møguleikin verður ofta ikki sæddur, tí hann er í arbeiðsklæðum og líkist arbeiði', E'People overlook chances when they arrive disguised as effort.', E'Folk overser ofte chancer, når de ligner indsats.', E'People overlook chances when they arrive disguised as effort.', E'People overlook chances when they arrive disguised as effort.', E'People overlook chances when they arrive disguised as effort.', E'People overlook chances when they arrive disguised as effort.', E'People overlook chances when they arrive disguised as effort.', E'People overlook chances when they arrive disguised as effort.', E'Fólk síggja ofta ikki møguleikar, tá teir líkjast stríði.'),
  (E'perfect-enemy-good', null, E'work-results', 0, E'2026-06-03T20:37:15.156718+00:00', E'Perfect is the enemy of good', E'Det perfekte er det godes fjende', E'Perfect is the enemy of good', E'Perfect is the enemy of good', E'Perfect is the enemy of good', E'Perfect is the enemy of good', E'Perfect is the enemy of good', E'Perfect is the enemy of good', E'Tað fullkomna er fíggindi hjá tí góða', E'Trying to make something perfect can prevent it from becoming useful.', E'Jagten på det perfekte kan forhindre noget godt i at blive færdigt.', E'Trying to make something perfect can prevent it from becoming useful.', E'Trying to make something perfect can prevent it from becoming useful.', E'Trying to make something perfect can prevent it from becoming useful.', E'Trying to make something perfect can prevent it from becoming useful.', E'Trying to make something perfect can prevent it from becoming useful.', E'Trying to make something perfect can prevent it from becoming useful.', E'Jagstranin eftir tí fullkomna kann forða tí góða í at verða liðugt.'),
  (E'wish-in-one-hand', null, E'work-results', 0, E'2026-06-03T20:37:16.156718+00:00', E'Wish in one hand, shit in the other; see which fills up first', E'Ønsk i den ene hånd og skidt i den anden — se hvilken der fyldes først', E'Wish in one hand, shit in the other; see which fills up first', E'Wish in one hand, shit in the other; see which fills up first', E'Wish in one hand, shit in the other; see which fills up first', E'Wish in one hand, shit in the other; see which fills up first', E'Wish in one hand, shit in the other; see which fills up first', E'Wish in one hand, shit in the other; see which fills up first', E'Ynsk í aðra hondina og skít í hina — hygg hvør fyllist fyrst', E'Wishing does not produce results; action does.', E'Ønsker skaber ikke resultater; handling gør.', E'Wishing does not produce results; action does.', E'Wishing does not produce results; action does.', E'Wishing does not produce results; action does.', E'Wishing does not produce results; action does.', E'Wishing does not produce results; action does.', E'Wishing does not produce results; action does.', E'Ynski skapa ikki úrslit; gerðir gera.'),
  (E'nothing-ventured', null, E'work-results', 0, E'2026-06-03T20:37:17.156718+00:00', E'Nothing ventured, nothing gained', E'Hvo intet vover, intet vinder', E'Wer nicht wagt, der nicht gewinnt', E'Quien no arriesga, no gana', E'Den som intet våger, intet vinner', E'Qui non audet, non vincit', E'Chi non risica non rosica', E'Qui ne risque rien n’a rien', E'Tann ið einki váðar, einki vinnur', E'You must take chances to gain something.', E'Man må tage chancer for at vinde noget.', E'You must take chances to gain something.', E'You must take chances to gain something.', E'You must take chances to gain something.', E'You must take chances to gain something.', E'You must take chances to gain something.', E'You must take chances to gain something.', E'Tú mást váða nakað fyri at vinna nakað.'),
  (E'rome-not-built-day', null, E'work-results', 0, E'2026-06-03T20:37:18.156718+00:00', E'Rome was not built in a day', E'Rom blev ikke bygget på én dag', E'Rom wurde nicht an einem Tag erbaut', E'Roma no se hizo en un día', E'Roma ble ikke bygget på én dag', E'Roma uno die non est condita', E'Roma non fu fatta in un giorno', E'Rome ne s’est pas faite en un jour', E'Róm varð ikki bygdur eftir einum degi', E'Big things take time.', E'Store ting tager tid.', E'Big things take time.', E'Big things take time.', E'Big things take time.', E'Big things take time.', E'Big things take time.', E'Big things take time.', E'Stór ting taka tíð.'),
  (E'push-envelope', null, E'work-results', 0, E'2026-06-03T20:37:19.156718+00:00', E'Push the envelope', E'Skubbe konvolutten', E'Den Umschlag schieben', E'Empujar el sobre', E'Skyve konvolutten', E'Involucrum pellere', E'Spingere la busta', E'Pousser l’enveloppe', E'Skumpa brævbjálvan', E'To test or go beyond normal limits.', E'At teste eller gå ud over normale grænser.', E'To test or go beyond normal limits.', E'To test or go beyond normal limits.', E'To test or go beyond normal limits.', E'To test or go beyond normal limits.', E'To test or go beyond normal limits.', E'To test or go beyond normal limits.', E'At royna ella fara út um vanlig mørk.'),
  (E'honesty-best-policy', null, E'truth', 0, E'2026-06-03T20:37:20.156718+00:00', E'Honesty is the best policy', E'Ærlighed varer længst', E'Ehrlich währt am längsten', E'La honestidad es la mejor política', E'Ærlighet varer lengst', E'Honestas optima est ratio', E'L’onestà è la migliore politica', E'L’honnêteté est la meilleure politique', E'Ærligheit varir longst', E'It is usually best to tell the truth.', E'Det er som regel bedst at sige sandheden.', E'It is usually best to tell the truth.', E'It is usually best to tell the truth.', E'It is usually best to tell the truth.', E'It is usually best to tell the truth.', E'It is usually best to tell the truth.', E'It is usually best to tell the truth.', E'Tað er vanliga best at siga sannleikan.'),
  (E'truth-will-out', null, E'truth', 0, E'2026-06-03T20:37:21.156718+00:00', E'The truth will out', E'Sandheden kommer for en dag', E'Die Wahrheit kommt ans Licht', E'La verdad siempre sale a la luz', E'Sannheten kommer for en dag', E'Veritas temporis filia', E'La verità viene sempre a galla', E'La vérité finit toujours par éclater', E'Sannleikin kemur fyri ein dag', E'The truth usually becomes known eventually.', E'Sandheden bliver som regel kendt til sidst.', E'The truth usually becomes known eventually.', E'The truth usually becomes known eventually.', E'The truth usually becomes known eventually.', E'The truth usually becomes known eventually.', E'The truth usually becomes known eventually.', E'The truth usually becomes known eventually.', E'Sannleikin kemur vanliga fram at enda.'),
  (E'no-smoke-without-fire', null, E'truth', 0, E'2026-06-03T20:37:22.156718+00:00', E'Where there’s smoke, there’s fire', E'Ingen røg uden ild', E'Wo Rauch ist, ist auch Feuer', E'Cuando el río suena, agua lleva', E'Ingen røyk uten ild', E'Non est fumus absque igne', E'Non c’è fumo senza arrosto', E'Il n’y a pas de fumée sans feu', E'Eingin roykur uttan eld', E'Rumors often have a reason behind them.', E'Rygter har ofte en årsag bag sig.', E'Rumors often have a reason behind them.', E'Rumors often have a reason behind them.', E'Rumors often have a reason behind them.', E'Rumors often have a reason behind them.', E'Rumors often have a reason behind them.', E'Rumors often have a reason behind them.', E'Søgur hava ofta eina orsøk aftanfyri seg.'),
  (E'elephant-room', null, E'truth', 0, E'2026-06-03T20:37:23.156718+00:00', E'The elephant in the room', E'Elefanten i rummet', E'Der Elefant im Raum', E'El elefante en la habitación', E'Elefanten i rommet', E'Elephantus in cubiculo', E'L’elefante nella stanza', E'L’éléphant dans la pièce', E'Elefanturin í rúminum', E'An obvious problem nobody wants to talk about.', E'Et tydeligt problem, som ingen vil tale om.', E'An obvious problem nobody wants to talk about.', E'An obvious problem nobody wants to talk about.', E'An obvious problem nobody wants to talk about.', E'An obvious problem nobody wants to talk about.', E'An obvious problem nobody wants to talk about.', E'An obvious problem nobody wants to talk about.', E'Ein eyðsýndur trupulleiki, sum eingin vil tosa um.'),
  (E'beat-around-bush', null, E'truth', 0, E'2026-06-03T20:37:24.156718+00:00', E'Beat around the bush', E'Gå som katten om den varme grød', E'Um den heißen Brei herumreden', E'Andarse por las ramas', E'Gå rundt grøten', E'Rem non attingere', E'Girarci intorno', E'Tourner autour du pot', E'Sláa rundan um runnin', E'To avoid saying the main point directly.', E'At undgå at sige det vigtigste direkte.', E'To avoid saying the main point directly.', E'To avoid saying the main point directly.', E'To avoid saying the main point directly.', E'To avoid saying the main point directly.', E'To avoid saying the main point directly.', E'To avoid saying the main point directly.', E'At sleppa undan at siga høvuðspunktið beinleiðis.'),
  (E'horses-mouth', null, E'truth', 0, E'2026-06-03T20:37:25.156718+00:00', E'Straight from the horse’s mouth', E'Fra hestens mund', E'Direkt aus dem Maul des Pferdes', E'Directamente de la boca del caballo', E'Rett fra hestens munn', E'Ex ore equi ipso', E'Direttamente dalla bocca del cavallo', E'Directement de la bouche du cheval', E'Beint úr rossamunninum', E'Information from the most direct or reliable source.', E'Information fra den mest direkte eller troværdige kilde.', E'Information from the most direct or reliable source.', E'Information from the most direct or reliable source.', E'Information from the most direct or reliable source.', E'Information from the most direct or reliable source.', E'Information from the most direct or reliable source.', E'Information from the most direct or reliable source.', E'Upplýsingar frá beinleiðis ella álítandi keldu.'),
  (E'turn-blind-eye', null, E'truth', 0, E'2026-06-03T20:37:26.156718+00:00', E'Turn a blind eye', E'Vende det blinde øje til', E'Ein Auge zudrücken', E'Hacer la vista gorda', E'Se gjennom fingrene med noe', E'Oculos claudere', E'Chiudere un occhio', E'Fermer les yeux sur quelque chose', E'Venda blinda eygað til', E'To deliberately ignore something you know is happening.', E'Bevidst at ignorere noget, man godt ved sker.', E'To deliberately ignore something you know is happening.', E'To deliberately ignore something you know is happening.', E'To deliberately ignore something you know is happening.', E'To deliberately ignore something you know is happening.', E'To deliberately ignore something you know is happening.', E'To deliberately ignore something you know is happening.', E'Tilvitað at lata sum einki, hóast tú veitst, hvat hendir.'),
  (E'walls-have-ears', null, E'truth', 0, E'2026-06-03T20:37:27.156718+00:00', E'Walls have ears', E'Væggene har ører', E'Wände haben Ohren', E'Las paredes oyen', E'Veggene har ører', E'Parietes aures habent', E'Anche i muri hanno orecchie', E'Les murs ont des oreilles', E'Veggirnir hava oyru', E'Be careful what you say; someone may be listening.', E'Pas på hvad du siger; nogen kan lytte med.', E'Be careful what you say; someone may be listening.', E'Be careful what you say; someone may be listening.', E'Be careful what you say; someone may be listening.', E'Be careful what you say; someone may be listening.', E'Be careful what you say; someone may be listening.', E'Be careful what you say; someone may be listening.', E'Ansar eftir hvat tú sigur; onkur kann lurta.'),
  (E'cat-got-tongue', null, E'truth', 0, E'2026-06-03T20:37:28.156718+00:00', E'Cat got your tongue?', E'Har katten taget din tunge?', E'Hat es dir die Sprache verschlagen?', E'¿Te ha comido la lengua el gato?', E'Har du mistet munn og mæle?', E'Cur taces?', E'Ti ha mangiato la lingua il gatto?', E'Tu as perdu ta langue ?', E'Hevur ketan tikið tunguna?', E'Said when someone is unusually silent or cannot answer.', E'Siges når nogen er usædvanligt tavs eller ikke kan svare.', E'Said when someone is unusually silent or cannot answer.', E'Said when someone is unusually silent or cannot answer.', E'Said when someone is unusually silent or cannot answer.', E'Said when someone is unusually silent or cannot answer.', E'Said when someone is unusually silent or cannot answer.', E'Said when someone is unusually silent or cannot answer.', E'Verður sagt, tá onkur er óvanliga tigandi ella ikki fær svarað.'),
  (E'not-my-circus', null, E'relations', 0, E'2026-06-03T20:37:29.156718+00:00', E'Not my circus, not my monkeys', E'Ikke mit cirkus, ikke mine aber', E'Not my circus, not my monkeys', E'Not my circus, not my monkeys', E'Not my circus, not my monkeys', E'Not my circus, not my monkeys', E'Not my circus, not my monkeys', E'Not my circus, not my monkeys', E'Ikki mítt sirkus, ikki mínar apar', E'Do not take responsibility for someone else’s chaos.', E'Tag ikke ansvar for andres kaos, hvis det ikke er dit.', E'Do not take responsibility for someone else’s chaos.', E'Do not take responsibility for someone else’s chaos.', E'Do not take responsibility for someone else’s chaos.', E'Do not take responsibility for someone else’s chaos.', E'Do not take responsibility for someone else’s chaos.', E'Do not take responsibility for someone else’s chaos.', E'Tak ikki ábyrgd av ruðuleikanum hjá øðrum, um hann ikki er tín.'),
  (E'fool-experience', null, E'relations', 0, E'2026-06-03T20:37:30.156718+00:00', E'A fool will drag you down to their level and beat you with experience', E'En tåbe trækker dig ned på sit niveau og slår dig med erfaring', E'A fool will drag you down to their level and beat you with experience', E'A fool will drag you down to their level and beat you with experience', E'A fool will drag you down to their level and beat you with experience', E'A fool will drag you down to their level and beat you with experience', E'A fool will drag you down to their level and beat you with experience', E'A fool will drag you down to their level and beat you with experience', E'Ein býttlingur dregur teg niður á sítt støði og vinnur við royndum', E'Do not waste energy arguing on terms set by someone unreasonable.', E'Spild ikke kræfter på at diskutere på urimelige menneskers præmisser.', E'Do not waste energy arguing on terms set by someone unreasonable.', E'Do not waste energy arguing on terms set by someone unreasonable.', E'Do not waste energy arguing on terms set by someone unreasonable.', E'Do not waste energy arguing on terms set by someone unreasonable.', E'Do not waste energy arguing on terms set by someone unreasonable.', E'Do not waste energy arguing on terms set by someone unreasonable.', E'Brúka ikki orku upp á at kjakast eftir treytunum hjá einum órímiligum persóni.'),
  (E'grudge-poison', null, E'relations', 0, E'2026-06-03T20:37:31.156718+00:00', E'Holding a grudge is like drinking poison and waiting for the other person to die', E'At bære nag er som at drikke gift og vente på at den anden dør', E'Holding a grudge is like drinking poison and waiting for the other person to die', E'Holding a grudge is like drinking poison and waiting for the other person to die', E'Holding a grudge is like drinking poison and waiting for the other person to die', E'Holding a grudge is like drinking poison and waiting for the other person to die', E'Holding a grudge is like drinking poison and waiting for the other person to die', E'Holding a grudge is like drinking poison and waiting for the other person to die', E'At bera agg er sum at drekka eitur og bíða eftir at hin doyr', E'Resentment hurts the person carrying it more than the target.', E'Nag skader ofte den, der bærer det, mere end den det er rettet mod.', E'Resentment hurts the person carrying it more than the target.', E'Resentment hurts the person carrying it more than the target.', E'Resentment hurts the person carrying it more than the target.', E'Resentment hurts the person carrying it more than the target.', E'Resentment hurts the person carrying it more than the target.', E'Resentment hurts the person carrying it more than the target.', E'Agg skaðar ofta tann, sum ber tað, meira enn tann tað er vent ímóti.'),
  (E'judge-insides-outsides', null, E'relations', 0, E'2026-06-03T20:37:32.156718+00:00', E'Do not judge your insides by other people’s outsides', E'Døm ikke dit indre efter andres ydre', E'Do not judge your insides by other people’s outsides', E'Do not judge your insides by other people’s outsides', E'Do not judge your insides by other people’s outsides', E'Do not judge your insides by other people’s outsides', E'Do not judge your insides by other people’s outsides', E'Do not judge your insides by other people’s outsides', E'Døm ikki títt innara eftir uttara hjá øðrum', E'Do not compare your private struggle with someone else’s public image.', E'Sammenlign ikke dine private kampe med andres offentlige facade.', E'Do not compare your private struggle with someone else’s public image.', E'Do not compare your private struggle with someone else’s public image.', E'Do not compare your private struggle with someone else’s public image.', E'Do not compare your private struggle with someone else’s public image.', E'Do not compare your private struggle with someone else’s public image.', E'Do not compare your private struggle with someone else’s public image.', E'Samanber ikki tínar privatu stríð við almennu myndina hjá øðrum.'),
  (E'hurt-people-hurt-people', null, E'relations', 0, E'2026-06-03T20:37:33.156718+00:00', E'Hurt people hurt people', E'Sårede mennesker sårer mennesker', E'Hurt people hurt people', E'Hurt people hurt people', E'Hurt people hurt people', E'Hurt people hurt people', E'Hurt people hurt people', E'Hurt people hurt people', E'Særd fólk særa fólk', E'Unhealed pain often gets passed on to others.', E'Uforløst smerte bliver ofte givet videre til andre.', E'Unhealed pain often gets passed on to others.', E'Unhealed pain often gets passed on to others.', E'Unhealed pain often gets passed on to others.', E'Unhealed pain often gets passed on to others.', E'Unhealed pain often gets passed on to others.', E'Unhealed pain often gets passed on to others.', E'Ógrødd pína verður ofta givin víðari til onnur.'),
  (E'compassion-self-friend', null, E'relations', 0, E'2026-06-03T20:37:34.156718+00:00', E'Be as compassionate with yourself as you would be with a good friend', E'Vær lige så omsorgsfuld mod dig selv som mod en god ven', E'Be as compassionate with yourself as you would be with a good friend', E'Be as compassionate with yourself as you would be with a good friend', E'Be as compassionate with yourself as you would be with a good friend', E'Be as compassionate with yourself as you would be with a good friend', E'Be as compassionate with yourself as you would be with a good friend', E'Be as compassionate with yourself as you would be with a good friend', E'Ver eins miskunnsamur við teg sjálvan sum við ein góðan vin', E'Treat yourself with the kindness you would naturally offer someone you care about.', E'Behandl dig selv med den venlighed, du ville give én du holder af.', E'Treat yourself with the kindness you would naturally offer someone you care about.', E'Treat yourself with the kindness you would naturally offer someone you care about.', E'Treat yourself with the kindness you would naturally offer someone you care about.', E'Treat yourself with the kindness you would naturally offer someone you care about.', E'Treat yourself with the kindness you would naturally offer someone you care about.', E'Treat yourself with the kindness you would naturally offer someone you care about.', E'Far við tær sjálvum við somu vælvild sum tú hevði givið einum, tær er góður við.'),
  (E'blood-thicker-water', null, E'relations', 0, E'2026-06-03T20:37:35.156718+00:00', E'Blood is thicker than water', E'Blod er tykkere end vand', E'Blut ist dicker als Wasser', E'La sangre tira', E'Blod er tykkere enn vann', E'Sanguis aqua densior est', E'Il sangue non è acqua', E'Les liens du sang sont les plus forts', E'Blóð er tjúkkari enn vatn', E'Family ties are often very strong.', E'Familiebånd er ofte meget stærke.', E'Family ties are often very strong.', E'Family ties are often very strong.', E'Family ties are often very strong.', E'Family ties are often very strong.', E'Family ties are often very strong.', E'Family ties are often very strong.', E'Familjubond eru ofta sera sterk.'),
  (E'birds-feather', null, E'relations', 0, E'2026-06-03T20:37:36.156718+00:00', E'Birds of a feather flock together', E'Lige børn leger bedst', E'Gleich und gleich gesellt sich gern', E'Dios los cría y ellos se juntan', E'Like barn leker best', E'Pares cum paribus facillime congregantur', E'Chi si somiglia si piglia', E'Qui se ressemble s’assemble', E'Lík børn spæla best', E'Similar people often spend time together.', E'Folk der ligner hinanden, finder ofte sammen.', E'Similar people often spend time together.', E'Similar people often spend time together.', E'Similar people often spend time together.', E'Similar people often spend time together.', E'Similar people often spend time together.', E'Similar people often spend time together.', E'Fólk sum líkjast, finna ofta saman.'),
  (E'opposites-attract', null, E'relations', 0, E'2026-06-03T20:37:37.156718+00:00', E'Opposites attract', E'Modsætninger mødes', E'Gegensätze ziehen sich an', E'Los polos opuestos se atraen', E'Motsetninger tiltrekker hverandre', E'Contraria contrariis alliciuntur', E'Gli opposti si attraggono', E'Les opposés s’attirent', E'Andsøgnir dragast at hvørjum øðrum', E'Very different people can be drawn to each other.', E'Meget forskellige mennesker kan tiltrækkes af hinanden.', E'Very different people can be drawn to each other.', E'Very different people can be drawn to each other.', E'Very different people can be drawn to each other.', E'Very different people can be drawn to each other.', E'Very different people can be drawn to each other.', E'Very different people can be drawn to each other.', E'Sera ymisk fólk kunnu dragast at hvørjum øðrum.'),
  (E'love-blind', null, E'relations', 0, E'2026-06-03T20:37:38.156718+00:00', E'Love is blind', E'Kærlighed gør blind', E'Liebe macht blind', E'El amor es ciego', E'Kjærlighet gjør blind', E'Amor caecus est', E'L’amore è cieco', E'L’amour est aveugle', E'Kærleiki ger blindan', E'Love can make people ignore faults.', E'Kærlighed kan få folk til at overse fejl.', E'Love can make people ignore faults.', E'Love can make people ignore faults.', E'Love can make people ignore faults.', E'Love can make people ignore faults.', E'Love can make people ignore faults.', E'Love can make people ignore faults.', E'Kærleiki kann fáa fólk at síggja burtur frá brekum.'),
  (E'all-eggs-one-basket', null, E'risk', 0, E'2026-06-03T20:37:39.156718+00:00', E'Don’t put all your eggs in one basket', E'Læg ikke alle æg i én kurv', E'Nicht alles auf eine Karte setzen', E'No poner todos los huevos en la misma cesta', E'Ikke legge alle eggene i én kurv', E'Noli omnia ova in uno corbe ponere', E'Non mettere tutte le uova nello stesso paniere', E'Il ne faut pas mettre tous ses œufs dans le même panier', E'Legg ikki øll eggini í eina kurv', E'Do not risk everything on one plan.', E'Sats ikke alt på én plan.', E'Do not risk everything on one plan.', E'Do not risk everything on one plan.', E'Do not risk everything on one plan.', E'Do not risk everything on one plan.', E'Do not risk everything on one plan.', E'Do not risk everything on one plan.', E'Set ikki alt upp á eina ætlan.'),
  (E'look-before-leap', null, E'risk', 0, E'2026-06-03T20:37:40.156718+00:00', E'Look before you leap', E'Se dig for, før du springer', E'Schau, bevor du springst', E'Mira antes de saltar', E'Se før du hopper', E'Aspice antequam salias', E'Guarda prima di saltare', E'Regarde avant de sauter', E'Hygg áðrenn tú leypir', E'Think before you act.', E'Tænk dig om, før du handler.', E'Think before you act.', E'Think before you act.', E'Think before you act.', E'Think before you act.', E'Think before you act.', E'Think before you act.', E'Hugsa teg um, áðrenn tú gert nakað.'),
  (E'better-one-bird', null, E'risk', 0, E'2026-06-03T20:37:41.156718+00:00', E'A bird in the hand is worth two in the bush', E'Hellere én fugl i hånden end ti på taget', E'Besser den Spatz in der Hand als die Taube auf dem Dach', E'Más vale pájaro en mano que ciento volando', E'Bedre med én fugl i hånden enn ti på taket', E'Melior est avis in manu quam duae in silva', E'Meglio un uovo oggi che una gallina domani', E'Un tiens vaut mieux que deux tu l’auras', E'Betri ein fuglur í hond enn tíggju á takinum', E'A sure thing is better than a risky possibility.', E'Noget sikkert er bedre end en usikker mulighed.', E'A sure thing is better than a risky possibility.', E'A sure thing is better than a risky possibility.', E'A sure thing is better than a risky possibility.', E'A sure thing is better than a risky possibility.', E'A sure thing is better than a risky possibility.', E'A sure thing is better than a risky possibility.', E'Okkurt trygt er betri enn ein óvissur møguleiki.'),
  (E'bite-the-bullet', null, E'risk', 0, E'2026-06-03T20:37:42.156718+00:00', E'Bite the bullet', E'Bide i kuglen', E'In die Kugel beißen', E'Morder la bala', E'Bite i kula', E'Glans mordere', E'Mordere il proiettile', E'Mordre la balle', E'Bíta í kúluna', E'To accept something painful or difficult and get through it.', E'At acceptere noget svært eller ubehageligt og komme igennem det.', E'To accept something painful or difficult and get through it.', E'To accept something painful or difficult and get through it.', E'To accept something painful or difficult and get through it.', E'To accept something painful or difficult and get through it.', E'To accept something painful or difficult and get through it.', E'To accept something painful or difficult and get through it.', E'At taka okkurt trupult ella pínufult á seg og koma ígjøgnum tað.'),
  (E'cold-feet', null, E'risk', 0, E'2026-06-03T20:37:43.156718+00:00', E'Get cold feet', E'Få kolde fødder', E'Kalte Füße bekommen', E'Echarse atrás', E'Få kalde føtter', E'Animum demittere', E'Tirarsi indietro', E'Se dégonfler', E'Fáa kaldar føtur', E'To lose courage or confidence before doing something.', E'At miste modet lige før man skal gøre noget.', E'To lose courage or confidence before doing something.', E'To lose courage or confidence before doing something.', E'To lose courage or confidence before doing something.', E'To lose courage or confidence before doing something.', E'To lose courage or confidence before doing something.', E'To lose courage or confidence before doing something.', E'At missa dirvið beint áðrenn tú skalt gera okkurt.'),
  (E'put-on-spot', null, E'risk', 0, E'2026-06-03T20:37:44.156718+00:00', E'Be put on the spot', E'Blive sat på stedet', E'Jemanden in die Zwickmühle bringen', E'Poner a alguien en un aprieto', E'Sette noen på plass', E'In angustias aliquem adducere', E'Mettere qualcuno alle strette', E'Mettre quelqu’un sur la sellette', E'Verða settur á staðið', E'To be forced to answer or act in an awkward situation.', E'At blive tvunget til at svare eller handle i en presset situation.', E'To be forced to answer or act in an awkward situation.', E'To be forced to answer or act in an awkward situation.', E'To be forced to answer or act in an awkward situation.', E'To be forced to answer or act in an awkward situation.', E'To be forced to answer or act in an awkward situation.', E'To be forced to answer or act in an awkward situation.', E'At verða noyddur at svara ella gera okkurt í einari kroystari støðu.'),
  (E'running-from-to-why', null, E'risk', 0, E'2026-06-03T20:37:45.156718+00:00', E'Learn what you are running from, and to, and why', E'Find ud af hvad du løber fra, hvad du løber imod, og hvorfor', E'Learn what you are running from, and to, and why', E'Learn what you are running from, and to, and why', E'Learn what you are running from, and to, and why', E'Learn what you are running from, and to, and why', E'Learn what you are running from, and to, and why', E'Learn what you are running from, and to, and why', E'Finn út av hvat tú rennur frá, hvat tú rennur ímóti, og hví', E'Understand your motives before life passes you by.', E'Forstå dine motiver, før livet bare bliver bevægelse.', E'Understand your motives before life passes you by.', E'Understand your motives before life passes you by.', E'Understand your motives before life passes you by.', E'Understand your motives before life passes you by.', E'Understand your motives before life passes you by.', E'Understand your motives before life passes you by.', E'Skil tíni motiv, áðrenn lívið bara verður rørslu.'),
  (E'go-bananas', null, E'images-humour', 0, E'2026-06-03T20:37:46.156718+00:00', E'Go bananas', E'Gå bananas', E'Bananen gehen', E'Irse bananas', E'Gå bananas', E'Ad bananas ire', E'Andare bananas', E'Partir en bananes', E'Fara bananas', E'To become very excited, angry, or wild.', E'At blive meget begejstret, vred eller vild.', E'To become very excited, angry, or wild.', E'To become very excited, angry, or wild.', E'To become very excited, angry, or wild.', E'To become very excited, angry, or wild.', E'To become very excited, angry, or wild.', E'To become very excited, angry, or wild.', E'At gerast sera spentur, illur ella villur.'),
  (E'hangry', null, E'images-humour', 0, E'2026-06-03T20:37:47.156718+00:00', E'Hangry', E'Sulten og sur', E'Hungrig und schlecht gelaunt', E'De malas por hambre', E'Sulten og sint', E'Fame iratus', E'Arrabbiato per la fame', E'Irritable parce qu’on a faim', E'Svangaður og illur', E'Irritable or angry because you are hungry.', E'Irriteret eller vred, fordi man er sulten.', E'Irritable or angry because you are hungry.', E'Irritable or angry because you are hungry.', E'Irritable or angry because you are hungry.', E'Irritable or angry because you are hungry.', E'Irritable or angry because you are hungry.', E'Irritable or angry because you are hungry.', E'Irriteraður ella illur, tí tú ert svangur.'),
  (E'ghost-someone', null, E'images-humour', 0, E'2026-06-03T20:37:48.156718+00:00', E'To ghost someone', E'At ghoste nogen', E'Jemanden ghosten', E'Hacer ghosting a alguien', E'Å ghoste noen', E'Subito tacere atque evanescere', E'Ghostare qualcuno', E'Ghoster quelqu’un', E'At ghosta onkran', E'To suddenly stop replying to someone without explanation.', E'Pludselig at stoppe med at svare nogen uden forklaring.', E'To suddenly stop replying to someone without explanation.', E'To suddenly stop replying to someone without explanation.', E'To suddenly stop replying to someone without explanation.', E'To suddenly stop replying to someone without explanation.', E'To suddenly stop replying to someone without explanation.', E'To suddenly stop replying to someone without explanation.', E'Brádliga at gevast at svara onkrum uttan frágreiðing.'),
  (E'throw-shade', null, E'images-humour', 0, E'2026-06-03T20:37:49.156718+00:00', E'Throw shade', E'Kaste skygge', E'Einen Seitenhieb verteilen', E'Lanzar indirectas', E'Komme med stikk', E'Oblique maledicere', E'Lanciare frecciatine', E'Lancer des piques', E'Kasta skugga', E'To subtly criticize or show disrespect.', E'At kritisere eller vise mangel på respekt på en indirekte måde.', E'To subtly criticize or show disrespect.', E'To subtly criticize or show disrespect.', E'To subtly criticize or show disrespect.', E'To subtly criticize or show disrespect.', E'To subtly criticize or show disrespect.', E'To subtly criticize or show disrespect.', E'At finnast at ella vísa vanvirðing á ein óbeinleiðis hátt.'),
  (E'earworm', null, E'images-humour', 0, E'2026-06-03T20:37:50.156718+00:00', E'Earworm', E'Ørehænger', E'Ohrwurm', E'Una canción pegadiza', E'Øreorm', E'Canticum in mente haerens', E'Un tormentone', E'Un ver d’oreille', E'Oyraormur', E'A song or phrase that gets stuck in your head.', E'En sang eller sætning, der sætter sig fast i hovedet.', E'A song or phrase that gets stuck in your head.', E'A song or phrase that gets stuck in your head.', E'A song or phrase that gets stuck in your head.', E'A song or phrase that gets stuck in your head.', E'A song or phrase that gets stuck in your head.', E'A song or phrase that gets stuck in your head.', E'Ein sangur ella setningur, sum setur seg fastan í høvdinum.'),
  (E'hair-of-dog', null, E'images-humour', 0, E'2026-06-03T20:37:51.156718+00:00', E'Hair of the dog', E'En reparationsbajer', E'Konterbier', E'Curar la resaca con más alcohol', E'Reparasjonsøl', E'Similia similibus curantur', E'Chiodo scaccia chiodo', E'Soigner le mal par le mal', E'Hár av hundinum', E'Drinking more alcohol to ease a hangover.', E'At drikke mere alkohol for at dulme tømmermænd.', E'Drinking more alcohol to ease a hangover.', E'Drinking more alcohol to ease a hangover.', E'Drinking more alcohol to ease a hangover.', E'Drinking more alcohol to ease a hangover.', E'Drinking more alcohol to ease a hangover.', E'Drinking more alcohol to ease a hangover.', E'At drekka meira fyri at linna timburmenn.'),
  (E'mad-as-hatter', null, E'images-humour', 0, E'2026-06-03T20:37:52.156718+00:00', E'Mad as a hatter', E'Skør som en hattemager', E'Nicht ganz dicht sein', E'Estar como una cabra', E'Gal som en hattemaker', E'Insanus velut pilearius', E'Matto come un cavallo', E'Fou à lier', E'Ørur sum ein hattamakari', E'Completely eccentric, strange, or mentally unbalanced.', E'Meget excentrisk, mærkelig eller ude af balance.', E'Completely eccentric, strange, or mentally unbalanced.', E'Completely eccentric, strange, or mentally unbalanced.', E'Completely eccentric, strange, or mentally unbalanced.', E'Completely eccentric, strange, or mentally unbalanced.', E'Completely eccentric, strange, or mentally unbalanced.', E'Completely eccentric, strange, or mentally unbalanced.', E'Sera løgin, ørkymlaður ella ójavnur.'),
  (E'wet-blanket', null, E'images-humour', 0, E'2026-06-03T20:37:53.156718+00:00', E'A wet blanket', E'Et vådt tæppe', E'Eine nasse Decke', E'Una manta mojada', E'Et vått teppe', E'Stragulum madidum', E'Una coperta bagnata', E'Une couverture mouillée', E'Eitt vátt teppi', E'Someone who spoils other people’s fun or enthusiasm.', E'En person der ødelægger andres glæde eller entusiasme.', E'Someone who spoils other people’s fun or enthusiasm.', E'Someone who spoils other people’s fun or enthusiasm.', E'Someone who spoils other people’s fun or enthusiasm.', E'Someone who spoils other people’s fun or enthusiasm.', E'Someone who spoils other people’s fun or enthusiasm.', E'Someone who spoils other people’s fun or enthusiasm.', E'Ein persónur sum oyðileggur gleðina ella hugan hjá øðrum.'),
  (E'time-wounds-heels', null, E'images-humour', 0, E'2026-06-03T20:37:54.156718+00:00', E'Time wounds all heels', E'Tiden sårer alle skurke', E'Time wounds all heels', E'Time wounds all heels', E'Time wounds all heels', E'Time wounds all heels', E'Time wounds all heels', E'Time wounds all heels', E'Tíðin særir allar skálkar', E'Bad people may eventually face consequences.', E'Mennesker der opfører sig dårligt, kan med tiden møde konsekvenserne.', E'Bad people may eventually face consequences.', E'Bad people may eventually face consequences.', E'Bad people may eventually face consequences.', E'Bad people may eventually face consequences.', E'Bad people may eventually face consequences.', E'Bad people may eventually face consequences.', E'Fólk sum bera seg illa at, kunnu við tíðini møta avleiðingunum.'),
  (E'under-the-weather', null, E'images-humour', 0, E'2026-06-03T20:37:55.156718+00:00', E'Under the weather', E'Under vejret', E'Unter dem Wetter', E'Bajo el tiempo', E'Under været', E'Sub tempestate', E'Sotto il tempo', E'Sous le temps', E'Undir veðrinum', E'To feel ill, tired, or not quite yourself.', E'At føle sig syg, træt eller ikke helt som sig selv.', E'To feel ill, tired, or not quite yourself.', E'To feel ill, tired, or not quite yourself.', E'To feel ill, tired, or not quite yourself.', E'To feel ill, tired, or not quite yourself.', E'To feel ill, tired, or not quite yourself.', E'To feel ill, tired, or not quite yourself.', E'To feel ill, tired, or not quite yourself.'),
  (E'bull-china-shop', null, E'images-humour', 0, E'2026-06-03T20:37:56.156718+00:00', E'A bull in a china shop', E'Som en elefant i en glasbutik', E'Wie ein Elefant im Porzellanladen', E'Como un elefante en una cacharrería', E'Som en elefant i en glassbutikk', E'Vel bos in officina fictilium', E'Come un elefante in una cristalleria', E'Comme un éléphant dans un magasin de porcelaine', E'Sum ein tarvur í einum postulínshandli', E'Someone clumsy or careless who causes damage or chaos.', E'En klodset eller uforsigtig person, der skaber kaos.', E'Someone clumsy or careless who causes damage or chaos.', E'Someone clumsy or careless who causes damage or chaos.', E'Someone clumsy or careless who causes damage or chaos.', E'Someone clumsy or careless who causes damage or chaos.', E'Someone clumsy or careless who causes damage or chaos.', E'Someone clumsy or careless who causes damage or chaos.', E'Ein klombrutur ella óvarin persónur, sum ger skaða ella ruðuleika.'),
  (E'good-samaritan', null, E'origin-stories', 0, E'2026-06-03T20:37:57.156718+00:00', E'A good Samaritan', E'En barmhjertig samaritaner', E'Ein barmherziger Samariter', E'Un buen samaritano', E'En barmhjertig samaritan', E'Samaritanus misericors', E'Un buon samaritano', E'Un bon Samaritain', E'Ein miskunnsamur samverji', E'Someone who helps a stranger or person in need.', E'En person der hjælper en fremmed eller én i nød.', E'Someone who helps a stranger or person in need.', E'Someone who helps a stranger or person in need.', E'Someone who helps a stranger or person in need.', E'Someone who helps a stranger or person in need.', E'Someone who helps a stranger or person in need.', E'Someone who helps a stranger or person in need.', E'Ein persónur sum hjálpir einum fremmandum ella einum í neyð.'),
  (E'forbidden-fruit', null, E'origin-stories', 0, E'2026-06-03T20:37:58.156718+00:00', E'Forbidden fruit', E'Forbuden frugt', E'Verbotene Frucht', E'Fruta prohibida', E'Forbuden frukt', E'Fructus vetitus', E'Frutto proibito', E'Fruit défendu', E'Forboðin frukt', E'Something becomes more tempting because it is not allowed.', E'Noget bliver mere fristende, fordi det ikke er tilladt.', E'Something becomes more tempting because it is not allowed.', E'Something becomes more tempting because it is not allowed.', E'Something becomes more tempting because it is not allowed.', E'Something becomes more tempting because it is not allowed.', E'Something becomes more tempting because it is not allowed.', E'Something becomes more tempting because it is not allowed.', E'Okkurt verður meira freistandi, tí tað ikki er loyvt.'),
  (E'scapegoat', null, E'origin-stories', 0, E'2026-06-03T20:37:59.156718+00:00', E'Scapegoat', E'Syndebuk', E'Sündenbock', E'Chivo expiatorio', E'Syndebukk', E'Caper emissarius', E'Capro espiatorio', E'Bouc émissaire', E'Syndabukkur', E'A person or group blamed for something, often unfairly.', E'En person eller gruppe der får skylden, ofte uretfærdigt.', E'A person or group blamed for something, often unfairly.', E'A person or group blamed for something, often unfairly.', E'A person or group blamed for something, often unfairly.', E'A person or group blamed for something, often unfairly.', E'A person or group blamed for something, often unfairly.', E'A person or group blamed for something, often unfairly.', E'Ein persónur ella bólkur, sum fær skyldina, ofta órættvíst.'),
  (E'skin-of-teeth', null, E'origin-stories', 0, E'2026-06-03T20:38:00.156718+00:00', E'By the skin of your teeth', E'Med huden på tænderne', E'Mit Ach und Krach', E'Por los pelos', E'Med nød og neppe', E'Vix evasi', E'Per un pelo', E'De justesse', E'Við húðini á tonnunum', E'To only just succeed or escape.', E'At klare noget eller slippe væk lige akkurat.', E'To only just succeed or escape.', E'To only just succeed or escape.', E'To only just succeed or escape.', E'To only just succeed or escape.', E'To only just succeed or escape.', E'To only just succeed or escape.', E'At klára okkurt ella sleppa burtur akkurát.'),
  (E'read-riot-act', null, E'origin-stories', 0, E'2026-06-03T20:38:01.156718+00:00', E'Read the riot act', E'Læse nogen teksten', E'Jemandem die Leviten lesen', E'Cantarle las cuarenta a alguien', E'Lese noen teksten', E'Acriter obiurgare', E'Fare una ramanzina', E'Passer un savon à quelqu’un', E'Lesa onkrum lógina', E'To strongly warn or scold someone.', E'At give nogen en kraftig advarsel eller skideballe.', E'To strongly warn or scold someone.', E'To strongly warn or scold someone.', E'To strongly warn or scold someone.', E'To strongly warn or scold someone.', E'To strongly warn or scold someone.', E'To strongly warn or scold someone.', E'At geva onkrum eina harða ávaring ella skolu.'),
  (E'bury-hatchet', null, E'origin-stories', 0, E'2026-06-03T20:38:02.156718+00:00', E'Bury the hatchet', E'Begrave stridsøksen', E'Das Kriegsbeil begraben', E'Enterrar el hacha de guerra', E'Begrave stridsøksen', E'Bellum deponere', E'Seppellire l’ascia di guerra', E'Enterrer la hache de guerre', E'Grava stríðsøksina niður', E'To end a conflict and make peace.', E'At afslutte en konflikt og slutte fred.', E'To end a conflict and make peace.', E'To end a conflict and make peace.', E'To end a conflict and make peace.', E'To end a conflict and make peace.', E'To end a conflict and make peace.', E'To end a conflict and make peace.', E'At enda eina ósemju og gera frið.'),
  (E'bigwig', null, E'origin-stories', 0, E'2026-06-03T20:38:03.156718+00:00', E'A bigwig', E'En stor paryk', E'Ein hohes Tier', E'Un pez gordo', E'En stor kanon', E'Vir potens', E'Un pezzo grosso', E'Une grosse légume', E'Ein stórur parykkur', E'An important or powerful person.', E'En vigtig eller magtfuld person.', E'An important or powerful person.', E'An important or powerful person.', E'An important or powerful person.', E'An important or powerful person.', E'An important or powerful person.', E'An important or powerful person.', E'Ein týdningarmikil ella máttmikil persónur.'),
  (E'armed-to-teeth', null, E'origin-stories', 0, E'2026-06-03T20:38:04.156718+00:00', E'Armed to the teeth', E'Bevæbnet til tænderne', E'Bis an die Zähne bewaffnet', E'Armado hasta los dientes', E'Bevæpnet til tennene', E'Usque ad dentes armatus', E'Armato fino ai denti', E'Armé jusqu’aux dents', E'Vápnaður upp undir tenn', E'Fully equipped, especially with weapons or tools.', E'Fuldt udstyret, især med våben eller redskaber.', E'Fully equipped, especially with weapons or tools.', E'Fully equipped, especially with weapons or tools.', E'Fully equipped, especially with weapons or tools.', E'Fully equipped, especially with weapons or tools.', E'Fully equipped, especially with weapons or tools.', E'Fully equipped, especially with weapons or tools.', E'Fullkomiliga útgjørdur, serliga við vápnum ella amboðum.'),
  (E'silver-lining', null, E'origin-stories', 0, E'2026-06-03T20:38:05.156718+00:00', E'Every cloud has a silver lining', E'Hver sky har en sølvkant', E'Jede Wolke hat einen Silberrand', E'Cada nube tiene un borde de plata', E'Hver sky har en sølvkant', E'Omnis nubes marginem argenteum habet', E'Ogni nuvola ha un bordo d’argento', E'Chaque nuage a une bordure d’argent', E'Hvørt skýggj hevur eina ljósa rond', E'Even a bad situation may contain something positive.', E'Selv en dårlig situation kan indeholde noget positivt.', E'Even a bad situation may contain something positive.', E'Even a bad situation may contain something positive.', E'Even a bad situation may contain something positive.', E'Even a bad situation may contain something positive.', E'Even a bad situation may contain something positive.', E'Even a bad situation may contain something positive.', E'Sjálvt ein ring støða kann hava okkurt gott í sær.'),
  (E'you-live-and-learn', null, E'experience', 0, E'2026-06-03T20:38:06.156718+00:00', E'You live and you learn', E'Man lever og lærer', E'Man lernt nie aus', E'Viviendo se aprende', E'Man lærer så lenge man lever', E'Vivendo discimus', E'Non si finisce mai di imparare', E'On apprend tous les jours', E'Tú livir og lærir', E'Experience and mistakes teach you.', E'Fejl og oplevelser lærer en noget.', E'Experience and mistakes teach you.', E'Experience and mistakes teach you.', E'Experience and mistakes teach you.', E'Experience and mistakes teach you.', E'Experience and mistakes teach you.', E'Experience and mistakes teach you.', E'Mistøk og upplivingar læra teg nakað.'),
  (E'no-pain-no-gain', null, E'experience', 0, E'2026-06-03T20:38:07.156718+00:00', E'No pain, no gain', E'Ingen smerte, ingen gevinst', E'Ohne Fleiß kein Preis', E'Sin esfuerzo no hay recompensa', E'Uten innsats, ingen gevinst', E'Per aspera ad astra', E'Senza fatica non si ottiene nulla', E'On n’a rien sans rien', E'Eingin pína, eingin vinningur', E'Progress often requires effort.', E'Fremskridt kræver ofte indsats.', E'Progress often requires effort.', E'Progress often requires effort.', E'Progress often requires effort.', E'Progress often requires effort.', E'Progress often requires effort.', E'Progress often requires effort.', E'Framgongd krevur ofta stríð.'),
  (E'one-swallow', null, E'experience', 0, E'2026-06-03T20:38:08.156718+00:00', E'One swallow does not make a summer', E'Én svale gør ingen sommer', E'Eine Schwalbe macht noch keinen Sommer', E'Una golondrina no hace verano', E'Én svale gjør ingen sommer', E'Una hirundo non facit ver', E'Una rondine non fa primavera', E'Une hirondelle ne fait pas le printemps', E'Ein svala ger onga summar', E'One good sign does not prove everything is fine.', E'Et enkelt godt tegn beviser ikke, at alt er godt.', E'One good sign does not prove everything is fine.', E'One good sign does not prove everything is fine.', E'One good sign does not prove everything is fine.', E'One good sign does not prove everything is fine.', E'One good sign does not prove everything is fine.', E'One good sign does not prove everything is fine.', E'Eitt gott tekin prógvar ikki, at alt er gott.'),
  (E'all-that-glitters', null, E'experience', 0, E'2026-06-03T20:38:09.156718+00:00', E'All that glitters is not gold', E'Alt der glimter er ikke guld', E'Es ist nicht alles Gold, was glänzt', E'No es oro todo lo que reluce', E'Alt som glimrer er ikke gull', E'Non omne quod nitet aurum est', E'Non è tutto oro quel che luccica', E'Tout ce qui brille n’est pas or', E'Alt sum glitrar er ikki gull', E'Something attractive is not always valuable.', E'Noget der ser godt ud, er ikke altid værdifuldt.', E'Something attractive is not always valuable.', E'Something attractive is not always valuable.', E'Something attractive is not always valuable.', E'Something attractive is not always valuable.', E'Something attractive is not always valuable.', E'Something attractive is not always valuable.', E'Okkurt sum sær gott út, er ikki altíð virðismikið.'),
  (E'empty-vessels', null, E'experience', 0, E'2026-06-03T20:38:10.156718+00:00', E'Empty vessels make the most noise', E'Tomme tønder buldrer mest', E'Leere Fässer klingen hohl', E'Mucho ruido y pocas nueces', E'Tomme tønner buldrer mest', E'Vasa inania plurimum sonant', E'La botte vuota fa più rumore', E'Les tonneaux vides sont ceux qui font le plus de bruit', E'Tóm íløt ljóða mest', E'People with little knowledge can be the loudest.', E'Folk med lidt indhold kan larme mest.', E'People with little knowledge can be the loudest.', E'People with little knowledge can be the loudest.', E'People with little knowledge can be the loudest.', E'People with little knowledge can be the loudest.', E'People with little knowledge can be the loudest.', E'People with little knowledge can be the loudest.', E'Fólk við lítlari vitan kunnu vera mest harðmælt.'),
  (E'out-of-sight', null, E'experience', 0, E'2026-06-03T20:38:11.156718+00:00', E'Out of sight, out of mind', E'Ude af øje, ude af sind', E'Aus den Augen, aus dem Sinn', E'Ojos que no ven, corazón que no siente', E'Ute av syne, ute av sinn', E'Ab oculis, ab animo', E'Lontano dagli occhi, lontano dal cuore', E'Loin des yeux, loin du cœur', E'Úr eygsjón, úr huga', E'People often forget what they do not see.', E'Man glemmer ofte det, man ikke ser.', E'People often forget what they do not see.', E'People often forget what they do not see.', E'People often forget what they do not see.', E'People often forget what they do not see.', E'People often forget what they do not see.', E'People often forget what they do not see.', E'Fólk gloyma ofta tað, tey ikki síggja.'),
  (E'two-birds-one-stone', null, E'experience', 0, E'2026-06-03T20:38:12.156718+00:00', E'Kill two birds with one stone', E'Slå to fluer med ét smæk', E'Zwei Fliegen mit einer Klappe schlagen', E'Matar dos pájaros de un tiro', E'Slå to fluer i én smekk', E'Kill two birds with one stone', E'Prendere due piccioni con una fava', E'Faire d’une pierre deux coups', E'Sláa tvær flugur við einum smekki', E'Solve two things with one action.', E'Løse to ting med én handling.', E'Solve two things with one action.', E'Solve two things with one action.', E'Solve two things with one action.', E'Solve two things with one action.', E'Solve two things with one action.', E'Solve two things with one action.', E'Loysa tvey mál við einari gerð.'),
  (E'old-habits-die-hard', null, E'experience', 0, E'2026-06-03T20:38:13.156718+00:00', E'You can’t teach an old dog new tricks', E'Man kan ikke lære en gammel hund nye tricks', E'Einem alten Hund bringt man keine neuen Tricks bei', E'No se le enseñan trucos nuevos a un perro viejo', E'Man kan ikke lære en gammel hund nye triks', E'Canem senem novos dolos docere non potes', E'Non si insegnano nuovi trucchi a un cane vecchio', E'On n’apprend pas de nouveaux tours à un vieux chien', E'Tú kanst ikki læra ein gamlan hund nýggj kynstur', E'It is difficult to make someone change long-established habits or ways of thinking.', E'Det er svært at ændre gamle vaner eller tankemønstre.', E'It is difficult to make someone change long-established habits or ways of thinking.', E'It is difficult to make someone change long-established habits or ways of thinking.', E'It is difficult to make someone change long-established habits or ways of thinking.', E'It is difficult to make someone change long-established habits or ways of thinking.', E'It is difficult to make someone change long-established habits or ways of thinking.', E'It is difficult to make someone change long-established habits or ways of thinking.', E'Tað er torført at broyta gamlar vanar ella hugsanarhættir.'),
  (E'too-many-cooks', null, E'experience', 0, E'2026-06-03T20:38:14.156718+00:00', E'Too many cooks spoil the broth', E'For mange kokke fordærver maden', E'Viele Köche verderben den Brei', E'Muchas manos en un plato hacen mucho garabato', E'Dess flere kokker, dess mer søl', E'Multitudo coquorum pulmentum corrumpit', E'Troppi cuochi guastano la cucina', E'Trop de cuisiniers gâtent la sauce', E'Ov nógvir kokkar spilla matin', E'Too many people controlling something can make it worse.', E'For mange der bestemmer, kan gøre resultatet dårligere.', E'Too many people controlling something can make it worse.', E'Too many people controlling something can make it worse.', E'Too many people controlling something can make it worse.', E'Too many people controlling something can make it worse.', E'Too many people controlling something can make it worse.', E'Too many people controlling something can make it worse.', E'Ov nógv fólk við stýring kunnu gera úrslitið verri.'),
  (E'many-hands-light-work', null, E'experience', 0, E'2026-06-03T20:38:15.156718+00:00', E'Many hands make light work', E'Mange hænder gør arbejdet let', E'Viele Hände machen der Arbeit schnell ein Ende', E'Muchas manos hacen el trabajo ligero', E'Mange hender gjør arbeidet lett', E'Multae manus onus levant', E'Molte mani rendono il lavoro leggero', E'Beaucoup de mains rendent le travail léger', E'Mangar hendur gera arbeiðið lætt', E'A task is easier when more people help.', E'En opgave bliver lettere, når flere hjælper.', E'A task is easier when more people help.', E'A task is easier when more people help.', E'A task is easier when more people help.', E'A task is easier when more people help.', E'A task is easier when more people help.', E'A task is easier when more people help.', E'Ein uppgáva verður lættari, tá fleiri hjálpa.'),
  (E'silence-golden', null, E'experience', 0, E'2026-06-03T20:38:16.156718+00:00', E'Silence is golden', E'Tavshed er guld', E'Reden ist Silber, Schweigen ist Gold', E'El silencio es oro', E'Tale er sølv, taushet er gull', E'Silentium est aureum', E'Il silenzio è d’oro', E'La parole est d’argent, le silence est d’or', E'Tøgn er gull', E'Sometimes it is best not to speak.', E'Nogle gange er det bedst ikke at sige noget.', E'Sometimes it is best not to speak.', E'Sometimes it is best not to speak.', E'Sometimes it is best not to speak.', E'Sometimes it is best not to speak.', E'Sometimes it is best not to speak.', E'Sometimes it is best not to speak.', E'Onkuntíð er best ikki at siga nakað.'),
  (E'knowledge-power', null, E'experience', 0, E'2026-06-03T20:38:17.156718+00:00', E'Knowledge is power', E'Viden er magt', E'Wissen ist Macht', E'El conocimiento es poder', E'Kunnskap er makt', E'Scientia potentia est', E'Sapere è potere', E'Le savoir, c’est le pouvoir', E'Vitan er vald', E'Knowing more gives you strength and options.', E'Mere viden giver styrke og muligheder.', E'Knowing more gives you strength and options.', E'Knowing more gives you strength and options.', E'Knowing more gives you strength and options.', E'Knowing more gives you strength and options.', E'Knowing more gives you strength and options.', E'Knowing more gives you strength and options.', E'Meiri vitan gevur styrki og møguleikar.'),
  (E'every-beginning-hard', null, E'experience', 0, E'2026-06-03T20:38:18.156718+00:00', E'The first step is the hardest', E'Al begyndelse er svær', E'Aller Anfang ist schwer', E'Todos los comienzos son difíciles', E'All begynnelse er vanskelig', E'Omne initium difficile est', E'Tutti gli inizi sono difficili', E'Il n’y a que le premier pas qui coûte', E'Øll byrjan er torfør', E'Starting something new is often the most difficult part.', E'Det kan være svært at starte noget nyt.', E'Starting something new is often the most difficult part.', E'Starting something new is often the most difficult part.', E'Starting something new is often the most difficult part.', E'Starting something new is often the most difficult part.', E'Starting something new is often the most difficult part.', E'Starting something new is often the most difficult part.', E'Tað kann vera torført at byrja nakað nýtt.'),
  (E'pick-your-brain', null, E'experience', 0, E'2026-06-03T20:38:19.156718+00:00', E'Pick someone’s brain', E'Må jeg plukke lidt i din hjerne?', E'Darf ich dein Gehirn pflücken?', E'¿Puedo hurgar un poco en tu cerebro?', E'Kan jeg plukke litt i hjernen din?', E'Cerebrum tuum paululum carpere possum?', E'Posso pescare un po’ nel tuo cervello?', E'Je peux picorer un peu dans ton cerveau ?', E'Kann eg plukka eitt sindur í heilanum hjá tær?', E'To ask someone for advice, ideas, or knowledge.', E'En venlig måde at spørge nogen om råd, idéer eller viden.', E'To ask someone for advice, ideas, or knowledge.', E'To ask someone for advice, ideas, or knowledge.', E'To ask someone for advice, ideas, or knowledge.', E'To ask someone for advice, ideas, or knowledge.', E'To ask someone for advice, ideas, or knowledge.', E'To ask someone for advice, ideas, or knowledge.', E'To ask someone for advice, ideas, or knowledge.'),
  (E'bone-to-pick', null, E'experience', 0, E'2026-06-03T20:38:20.156718+00:00', E'Have a bone to pick', E'Jeg har et ben at pille med dig', E'Ich habe einen Knochen mit dir zu pflücken', E'Tengo un hueso que roer contigo', E'Jeg har et bein å plukke med deg', E'Os tecum carpere habeo', E'Ho un osso da spolpare con te', E'J’ai un os à ronger avec toi', E'Eg havi eitt bein at pilla við teg', E'To have a complaint or disagreement you want to discuss.', E'Du har en klage eller uenighed, som du vil tage op.', E'To have a complaint or disagreement you want to discuss.', E'To have a complaint or disagreement you want to discuss.', E'To have a complaint or disagreement you want to discuss.', E'To have a complaint or disagreement you want to discuss.', E'To have a complaint or disagreement you want to discuss.', E'To have a complaint or disagreement you want to discuss.', E'Tú hevur eina klagu ella ósemju, sum tú vilt taka upp.'),
  (E'break-the-ice', null, E'experience', 0, E'2026-06-03T20:38:21.156718+00:00', E'Break the ice', E'Bryde isen', E'Das Eis brechen', E'Romper el hielo', E'Bryte isen', E'Glaciem frangere', E'Rompere il ghiaccio', E'Briser la glace', E'Bróta ísin', E'To make a first meeting or awkward situation feel easier.', E'At gøre et første møde eller en akavet situation lettere.', E'To make a first meeting or awkward situation feel easier.', E'To make a first meeting or awkward situation feel easier.', E'To make a first meeting or awkward situation feel easier.', E'To make a first meeting or awkward situation feel easier.', E'To make a first meeting or awkward situation feel easier.', E'To make a first meeting or awkward situation feel easier.', E'At gera ein fyrsta fund ella eina ótrygga støðu lættari.'),
  (E'let-cat-out-bag', null, E'experience', 0, E'2026-06-03T20:38:22.156718+00:00', E'Let the cat out of the bag', E'Lukke katten ud af sækken', E'Die Katze aus dem Sack lassen', E'Descubrir el pastel', E'Slippe katten ut av sekken', E'Arcanum patefacere', E'Vuotare il sacco', E'Vendre la mèche', E'Lata ketuna úr sekkinum', E'To reveal a secret, often accidentally.', E'At afsløre en hemmelighed, ofte ved et uheld.', E'To reveal a secret, often accidentally.', E'To reveal a secret, often accidentally.', E'To reveal a secret, often accidentally.', E'To reveal a secret, often accidentally.', E'To reveal a secret, often accidentally.', E'To reveal a secret, often accidentally.', E'At avdúka eitt loyndarmál, ofta av óvart.'),
  (E'bite-dust', null, E'experience', 0, E'2026-06-03T20:38:23.156718+00:00', E'Bite the dust', E'Bide i støvet', E'Ins Gras beißen', E'Morder el polvo', E'Bite i gresset', E'Humum mordere', E'Mordere la polvere', E'Mordre la poussière', E'Bíta í dustið', E'To fail badly, fall, or die.', E'At fejle stort, falde eller dø.', E'To fail badly, fall, or die.', E'To fail badly, fall, or die.', E'To fail badly, fall, or die.', E'To fail badly, fall, or die.', E'To fail badly, fall, or die.', E'To fail badly, fall, or die.', E'At miseydnast illa, detta ella doyggja.')
on conflict (id) do update set
  image_url = excluded.image_url,
  category = excluded.category,
  favorite_count = excluded.favorite_count,
  created_at = excluded.created_at,
  quote_en = excluded.quote_en,
  quote_da = excluded.quote_da,
  quote_de = excluded.quote_de,
  quote_es = excluded.quote_es,
  quote_no = excluded.quote_no,
  quote_la = excluded.quote_la,
  quote_it = excluded.quote_it,
  quote_fr = excluded.quote_fr,
  quote_fo = excluded.quote_fo,
  description_en = excluded.description_en,
  description_da = excluded.description_da,
  description_de = excluded.description_de,
  description_es = excluded.description_es,
  description_no = excluded.description_no,
  description_la = excluded.description_la,
  description_it = excluded.description_it,
  description_fr = excluded.description_fr,
  description_fo = excluded.description_fo;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'proverb-images',
  'proverb-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
